In [25]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [26]:
df = pd.read_csv("cyclone_data.csv")

In [27]:
df.shape

(377719, 7)

In [28]:
df.head()

,time,Cyclone_Inlet_Gas_Temp,Cyclone_Material_Temp,Cyclone_Outlet_Gas_draft,Cyclone_cone_draft,Cyclone_Gas_Outlet_Temp,Cyclone_Inlet_Draft
0,01-01-2017 00:00,867.63,910.42,-189.54,-186.04,852.13,-145.9
1,01-01-2017 00:05,879.23,918.14,-184.33,-182.1,862.53,-149.76
2,01-01-2017 00:10,875.67,924.18,-181.26,-166.47,866.06,-145.01
3,01-01-2017 00:15,875.28,923.15,-179.15,-174.83,865.85,-142.82
4,01-01-2017 00:20,891.66,934.26,-178.32,-173.72,876.06,-143.39

In [29]:
df.columns

Index(['time', 'Cyclone_Inlet_Gas_Temp', 'Cyclone_Material_Temp',
       'Cyclone_Outlet_Gas_draft', 'Cyclone_cone_draft',
       'Cyclone_Gas_Outlet_Temp', 'Cyclone_Inlet_Draft'],
      dtype='str')

In [30]:
df.dtypes

time                        str
Cyclone_Inlet_Gas_Temp      str
Cyclone_Material_Temp       str
Cyclone_Outlet_Gas_draft    str
Cyclone_cone_draft          str
Cyclone_Gas_Outlet_Temp     str
Cyclone_Inlet_Draft         str
dtype: object

In [31]:
df.tail()

,time,Cyclone_Inlet_Gas_Temp,Cyclone_Material_Temp,Cyclone_Outlet_Gas_draft,Cyclone_cone_draft,Cyclone_Gas_Outlet_Temp,Cyclone_Inlet_Draft
377714,08-07-2020 11:55,899.42,919.79,-224.07,-209.77,901.01,-175.15
377715,08-07-2020 12:00,879.9,895.02,-228.04,-211.28,878.08,-176.94
377716,08-07-2020 12:05,887.2,895.7,-230.11,-214.65,885.32,-179.18
377717,08-07-2020 12:10,908.5,916.33,-231.51,-218.09,906.2,-181.96
377718,08-07-2020 12:15,880.86,905.31,-235.02,-219.44,882.1,-184.02

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 377719 entries, 0 to 377718
Data columns (total 7 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   time                      377719 non-null  str
 1   Cyclone_Inlet_Gas_Temp    377719 non-null  str
 2   Cyclone_Material_Temp     377719 non-null  str
 3   Cyclone_Outlet_Gas_draft  377719 non-null  str
 4   Cyclone_cone_draft        377719 non-null  str
 5   Cyclone_Gas_Outlet_Temp   377719 non-null  str
 6   Cyclone_Inlet_Draft       377719 non-null  str
dtypes: str(7)
memory usage: 20.2 MB

In [33]:
df.isna().sum()

time                        0
Cyclone_Inlet_Gas_Temp      0
Cyclone_Material_Temp       0
Cyclone_Outlet_Gas_draft    0
Cyclone_cone_draft          0
Cyclone_Gas_Outlet_Temp     0
Cyclone_Inlet_Draft         0
dtype: int64

In [34]:
for col in df.columns[1:]:
    print(f"\n--- {col} ---")
    print(df[col].value_counts().tail(10))

--- Cyclone_Inlet_Gas_Temp ---
Cyclone_Inlet_Gas_Temp
761.65     1
760        1
786.56     1
788.28     1
800.6      1
824.38     1
1012.84    1
1025.83    1
1028.53    1
986.66     1
Name: count, dtype: int64

--- Cyclone_Material_Temp ---
Cyclone_Material_Temp
589.78    1
564.37    1
625.38    1
712.18    1
794.8     1
836.78    1
784.81    1
780.52    1
801.17    1
823.93    1
Name: count, dtype: int64

--- Cyclone_Outlet_Gas_draft ---
Cyclone_Outlet_Gas_draft
-88.85     1
-97.96     1
-101.92    1
-106.97    1
-122.3     1
-132.11    1
-129.7     1
-153.23    1
-149.8     1
-294.94    1
Name: count, dtype: int64

--- Cyclone_cone_draft ---
Cyclone_cone_draft
-81.96     1
-84.78     1
-103.69    1
-126       1
-35.12     1
-48.28     1
-91.62     1
-110.59    1
-114.64    1
-117.29    1
Name: count, dtype: int64

--- Cyclone_Gas_Outlet_Temp ---
Cyclone_Gas_Outlet_Temp
747.42     1
745.62     1
744.64     1
741.53     1
1040.84    1
965.41     1
803.96     1
751.93     1
753.13     1
751.26     1
Name: count, dtype: int64

--- Cyclone_Inlet_Draft ---
Cyclone_Inlet_Draft
-81.32     1
-62.06     1
-73.53     1
-69.34     1
-81.1      1
-81.71     1
-101.88    1
-113.58    1
-126.52    1
-101.1     1
Name: count, dtype: int64

In [35]:
for col in sensor_cols:
    non_numeric = pd.to_numeric(df[col], errors="coerce").isna()
    print(f"\n--- {col} ---")
    print(df.loc[non_numeric, col].value_counts())

--- Cyclone_Inlet_Gas_Temp ---
Cyclone_Inlet_Gas_Temp
Not Connect     723
I/O Timeout     470
Configure       108
Scan Timeout     17
Comm Fail         2
Name: count, dtype: int64

--- Cyclone_Material_Temp ---
Cyclone_Material_Temp
Not Connect     723
I/O Timeout     470
Unit Down       271
Configure       108
Scan Timeout     17
Comm Fail         2
Name: count, dtype: int64

--- Cyclone_Outlet_Gas_draft ---
Cyclone_Outlet_Gas_draft
Not Connect     723
I/O Timeout     470
Configure       108
Scan Timeout     17
Comm Fail         2
Unit Down         1
Name: count, dtype: int64

--- Cyclone_cone_draft ---
Cyclone_cone_draft
Not Connect     723
I/O Timeout     470
Configure       108
Scan Timeout     17
Comm Fail         2
Name: count, dtype: int64

--- Cyclone_Gas_Outlet_Temp ---
Cyclone_Gas_Outlet_Temp
Not Connect     723
I/O Timeout     470
Configure       108
Scan Timeout     17
Comm Fail         2
Unit Down         1
Name: count, dtype: int64

--- Cyclone_Inlet_Draft ---
Cyclone_Inlet_Draft
Not Connect     723
I/O Timeout     470
Configure       108
Scan Timeout     17
Unit Down         2
Comm Fail         2
Name: count, dtype: int64

In [36]:
sensor_cols = [
    "Cyclone_Inlet_Gas_Temp",
    "Cyclone_Material_Temp",
    "Cyclone_Outlet_Gas_draft",
    "Cyclone_cone_draft",
    "Cyclone_Gas_Outlet_Temp",
    "Cyclone_Inlet_Draft"
]

In [37]:
for col in sensor_cols:
    non_numeric = pd.to_numeric(df[col], errors="coerce").isna()
    
    print(f"\n--- {col} ---")
    print(df.loc[non_numeric, col].value_counts())

--- Cyclone_Inlet_Gas_Temp ---
Cyclone_Inlet_Gas_Temp
Not Connect     723
I/O Timeout     470
Configure       108
Scan Timeout     17
Comm Fail         2
Name: count, dtype: int64

--- Cyclone_Material_Temp ---
Cyclone_Material_Temp
Not Connect     723
I/O Timeout     470
Unit Down       271
Configure       108
Scan Timeout     17
Comm Fail         2
Name: count, dtype: int64

--- Cyclone_Outlet_Gas_draft ---
Cyclone_Outlet_Gas_draft
Not Connect     723
I/O Timeout     470
Configure       108
Scan Timeout     17
Comm Fail         2
Unit Down         1
Name: count, dtype: int64

--- Cyclone_cone_draft ---
Cyclone_cone_draft
Not Connect     723
I/O Timeout     470
Configure       108
Scan Timeout     17
Comm Fail         2
Name: count, dtype: int64

--- Cyclone_Gas_Outlet_Temp ---
Cyclone_Gas_Outlet_Temp
Not Connect     723
I/O Timeout     470
Configure       108
Scan Timeout     17
Comm Fail         2
Unit Down         1
Name: count, dtype: int64

--- Cyclone_Inlet_Draft ---
Cyclone_Inlet_Draft
Not Connect     723
I/O Timeout     470
Configure       108
Scan Timeout     17
Unit Down         2
Comm Fail         2
Name: count, dtype: int64

In [ ]:
status_df = pd.DataFrame(index=df.index)#Preserve sensor status information

In [39]:
for col in sensor_cols:
    status_df[col] = df[col].where(
        ~pd.to_numeric(df[col], errors="coerce").isna(),
        df[col]
    )

In [ ]:
status_df = pd.DataFrame(index=df.index)#creating one status DataFrame

In [41]:
status_df = pd.DataFrame(index=df.index)
status_df.head()

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

standarizing the time

In [42]:
df["time"].head(10)

0    01-01-2017 00:00
1    01-01-2017 00:05
2    01-01-2017 00:10
3    01-01-2017 00:15
4    01-01-2017 00:20
5    01-01-2017 00:25
6    01-01-2017 00:30
7    01-01-2017 00:35
8    01-01-2017 00:40
9    01-01-2017 00:45
Name: time, dtype: str

In [43]:
df["time"].tail(10)

377709    08-07-2020 11:30
377710    08-07-2020 11:35
377711    08-07-2020 11:40
377712    08-07-2020 11:45
377713    08-07-2020 11:50
377714    08-07-2020 11:55
377715    08-07-2020 12:00
377716    08-07-2020 12:05
377717    08-07-2020 12:10
377718    08-07-2020 12:15
Name: time, dtype: str

In [44]:
df["time"] = pd.to_datetime(df["time"], errors="coerce")

In [45]:
df["time"].isna().sum()

np.int64(227235)

In [46]:
df["time"].dtype

dtype('<M8[us]')

In [47]:
df["time"].min(), df["time"].max()

(Timestamp('2017-01-01 00:00:00'), Timestamp('2020-08-07 12:15:00'))

In [49]:
time_diff = df["time"].diff()
time_diff.value_counts().head(10)

time
0 days 00:05:00    150440
Name: count, dtype: int64

In [ ]:
time_diff.sort_values(ascending=False).head(10)#largest timegap

1        0 days 00:05:00
253264   0 days 00:05:00
253248   0 days 00:05:00
253249   0 days 00:05:00
253250   0 days 00:05:00
253251   0 days 00:05:00
253252   0 days 00:05:00
253253   0 days 00:05:00
253254   0 days 00:05:00
253255   0 days 00:05:00
Name: time, dtype: timedelta64[us]

In [51]:
df["time"].duplicated().sum()

np.int64(227234)

In [52]:
time_diff = df["time"].diff()
print(time_diff.value_counts().head(10))

time
0 days 00:05:00    150440
Name: count, dtype: int64

In [53]:
print("Duplicate timestamps:", df["time"].duplicated().sum())

Duplicate timestamps: 227234

In [54]:
status_df = pd.DataFrame(index=df.index)

for col in sensor_cols:
    numeric = pd.to_numeric(df[col], errors="coerce")
    status_df[col + "_status"] = df[col].where(numeric.isna())

status_df.head()

,Cyclone_Inlet_Gas_Temp_status,Cyclone_Material_Temp_status,Cyclone_Outlet_Gas_draft_status,Cyclone_cone_draft_status,Cyclone_Gas_Outlet_Temp_status,Cyclone_Inlet_Draft_status
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
sensor_data = df[sensor_cols].apply(pd.to_numeric, errors="coerce")

sensor_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 377719 entries, 0 to 377718
Data columns (total 6 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Cyclone_Inlet_Gas_Temp    376399 non-null  float64
 1   Cyclone_Material_Temp     376128 non-null  float64
 2   Cyclone_Outlet_Gas_draft  376398 non-null  float64
 3   Cyclone_cone_draft        376399 non-null  float64
 4   Cyclone_Gas_Outlet_Temp   376398 non-null  float64
 5   Cyclone_Inlet_Draft       376397 non-null  float64
dtypes: float64(6)
memory usage: 17.3 MB

In [56]:
print(sensor_data.isna().sum())
print()
print(sensor_data.isna().mean().mul(100).round(3))

Cyclone_Inlet_Gas_Temp      1320
Cyclone_Material_Temp       1591
Cyclone_Outlet_Gas_draft    1321
Cyclone_cone_draft          1320
Cyclone_Gas_Outlet_Temp     1321
Cyclone_Inlet_Draft         1322
dtype: int64

Cyclone_Inlet_Gas_Temp      0.349
Cyclone_Material_Temp       0.421
Cyclone_Outlet_Gas_draft    0.350
Cyclone_cone_draft          0.349
Cyclone_Gas_Outlet_Temp     0.350
Cyclone_Inlet_Draft         0.350
dtype: float64

In [57]:
for col in status_df.columns:
    print(f"\n--- {col} ---")
    print(status_df[col].dropna().value_counts())

--- Cyclone_Inlet_Gas_Temp_status ---
Cyclone_Inlet_Gas_Temp_status
Not Connect     723
I/O Timeout     470
Configure       108
Scan Timeout     17
Comm Fail         2
Name: count, dtype: int64

--- Cyclone_Material_Temp_status ---
Cyclone_Material_Temp_status
Not Connect     723
I/O Timeout     470
Unit Down       271
Configure       108
Scan Timeout     17
Comm Fail         2
Name: count, dtype: int64

--- Cyclone_Outlet_Gas_draft_status ---
Cyclone_Outlet_Gas_draft_status
Not Connect     723
I/O Timeout     470
Configure       108
Scan Timeout     17
Comm Fail         2
Unit Down         1
Name: count, dtype: int64

--- Cyclone_cone_draft_status ---
Cyclone_cone_draft_status
Not Connect     723
I/O Timeout     470
Configure       108
Scan Timeout     17
Comm Fail         2
Name: count, dtype: int64

--- Cyclone_Gas_Outlet_Temp_status ---
Cyclone_Gas_Outlet_Temp_status
Not Connect     723
I/O Timeout     470
Configure       108
Scan Timeout     17
Comm Fail         2
Unit Down         1
Name: count, dtype: int64

--- Cyclone_Inlet_Draft_status ---
Cyclone_Inlet_Draft_status
Not Connect     723
I/O Timeout     470
Configure       108
Scan Timeout     17
Unit Down         2
Comm Fail         2
Name: count, dtype: int64

In [58]:
missing_by_row = sensor_data.isna().sum(axis=1)

print(missing_by_row.value_counts().sort_index())

0    376124
1       275
6      1320
Name: count, dtype: int64

In [59]:
status_only = status_df.dropna(how="all")
print(status_only.head(10))

     Cyclone_Inlet_Gas_Temp_status Cyclone_Material_Temp_status  \
2471                   I/O Timeout                  I/O Timeout
2472                   I/O Timeout                  I/O Timeout
2473                   I/O Timeout                  I/O Timeout
2474                   I/O Timeout                  I/O Timeout
2475                   I/O Timeout                  I/O Timeout
2476                   I/O Timeout                  I/O Timeout
2477                   I/O Timeout                  I/O Timeout
2478                   I/O Timeout                  I/O Timeout
2479                   I/O Timeout                  I/O Timeout
2480                   I/O Timeout                  I/O Timeout

     Cyclone_Outlet_Gas_draft_status Cyclone_cone_draft_status  \
2471                     I/O Timeout               I/O Timeout
2472                     I/O Timeout               I/O Timeout
2473                     I/O Timeout               I/O Timeout
2474                     I/O Timeout               I/O Timeout
2475                     I/O Timeout               I/O Timeout
2476                     I/O Timeout               I/O Timeout
2477                     I/O Timeout               I/O Timeout
2478                     I/O Timeout               I/O Timeout
2479                     I/O Timeout               I/O Timeout
2480                     I/O Timeout               I/O Timeout

     Cyclone_Gas_Outlet_Temp_status Cyclone_Inlet_Draft_status
2471                    I/O Timeout                I/O Timeout
2472                    I/O Timeout                I/O Timeout
2473                    I/O Timeout                I/O Timeout
2474                    I/O Timeout                I/O Timeout
2475                    I/O Timeout                I/O Timeout
2476                    I/O Timeout                I/O Timeout
2477                    I/O Timeout                I/O Timeout
2478                    I/O Timeout                I/O Timeout
2479                    I/O Timeout                I/O Timeout
2480                    I/O Timeout                I/O Timeout

In [60]:
sensor_data.describe().T

,count,mean,std,min,25%,50%,75%,max
Cyclone_Inlet_Gas_Temp,376399.0,727.348549,328.664814,0.00,856.2700,882.380,901.11,1157.63
Cyclone_Material_Temp,376128.0,750.830483,350.921068,-185.00,867.6675,913.360,943.66,1375.00
Cyclone_Outlet_Gas_draft,376398.0,-177.820685,99.147236,-456.66,-247.1900,-215.260,-170.13,40.27
Cyclone_cone_draft,376399.0,-164.572619,90.103023,-459.31,-226.7700,-198.560,-143.64,488.86
Cyclone_Gas_Outlet_Temp,376398.0,715.759972,325.346446,13.79,801.9600,871.525,899.30,1375.00
Cyclone_Inlet_Draft,376397.0,-141.302857,77.615576,-396.37,-193.5100,-169.460,-136.29,41.64

In [61]:
for col in sensor_cols:
    print(col, "zeros =", (sensor_data[col] == 0).sum())

Cyclone_Inlet_Gas_Temp zeros = 3
Cyclone_Material_Temp zeros = 14226
Cyclone_Outlet_Gas_draft zeros = 47
Cyclone_cone_draft zeros = 191
Cyclone_Gas_Outlet_Temp zeros = 0
Cyclone_Inlet_Draft zeros = 89

In [62]:
for col in sensor_cols:
    print(col, "negative =", (sensor_data[col] < 0).sum())

Cyclone_Inlet_Gas_Temp negative = 0
Cyclone_Material_Temp negative = 84
Cyclone_Outlet_Gas_draft negative = 318244
Cyclone_cone_draft negative = 352307
Cyclone_Gas_Outlet_Temp negative = 0
Cyclone_Inlet_Draft negative = 351430

In [63]:
material_zero = sensor_data["Cyclone_Material_Temp"] == 0

print("Number of zero readings:", material_zero.sum())

print(
    df.loc[
        material_zero,
        ["time"] + sensor_cols
    ].head(20)
)

Number of zero readings: 14226
                     time Cyclone_Inlet_Gas_Temp Cyclone_Material_Temp  \
5297                  NaT                 919.53                     0
5298                  NaT                 919.57                     0
5299                  NaT                 949.91                     0
5300                  NaT                 878.66                     0
5301                  NaT                 975.35                     0
15828                 NaT                 916.07                     0
17079 2017-03-01 07:15:00                 876.05                     0
19783 2017-03-10 16:35:00                 891.95                     0
19784 2017-03-10 16:40:00                 883.46                     0
19785 2017-03-10 16:45:00                 877.57                     0
25680                 NaT                 892.96                     0
25681                 NaT                 900.24                     0
58506                 NaT                 941.67                     0
58507                 NaT                 914.64                     0
58509                 NaT                 897.81                     0
58510                 NaT                 886.42                     0
63056 2017-08-07 22:40:00                 875.94                     0
70803 2017-09-03 20:15:00                 866.37                     0
71111 2017-09-04 21:55:00                 889.85                     0
72330 2017-09-09 03:30:00                 849.33                     0

      Cyclone_Outlet_Gas_draft Cyclone_cone_draft Cyclone_Gas_Outlet_Temp  \
5297                   -126.58            -125.95                  856.92
5298                   -137.13            -130.29                  856.56
5299                   -145.76            -138.34                  882.04
5300                   -141.86            -135.91                  845.87
5301                   -153.94            -149.47                  888.67
15828                  -203.09            -217.23                   881.3
17079                     -192            -104.98                  865.29
19783                  -175.14            -172.17                  899.95
19784                   -177.3            -176.55                  892.11
19785                  -177.71            -174.58                  885.63
25680                  -212.45            -149.63                   900.4
25681                  -211.15            -208.03                  909.78
58506                  -211.06            -233.22                   916.9
58507                  -203.98            -228.56                  925.78
58509                  -204.33            -236.77                  893.77
58510                  -197.29            -220.12                  896.33
63056                  -210.83            -203.74                  895.95
70803                  -173.94            -193.29                  869.46
71111                  -197.25            -214.07                  881.64
72330                  -176.01            -200.82                  867.41

      Cyclone_Inlet_Draft
5297               -94.75
5298              -101.49
5299              -108.68
5300              -103.69
5301              -118.99
15828             -170.09
17079             -152.51
19783             -143.48
19784              -154.6
19785             -151.67
25680             -162.25
25681             -161.78
58506             -172.74
58507             -164.58
58509             -171.35
58510             -160.12
63056             -164.31
70803             -151.21
71111             -176.03
72330             -154.63

In [64]:
zero_times = df.loc[material_zero, "time"]

print("First zero:", zero_times.min())
print("Last zero:", zero_times.max())

First zero: 2017-03-01 07:15:00
Last zero: 2019-10-12 23:55:00

In [65]:
print(
    df.loc[
        material_zero,
        sensor_cols
    ].describe().T
)

                          count unique    top   freq
Cyclone_Inlet_Gas_Temp    14226   2646  29.12     59
Cyclone_Material_Temp     14226      1      0  14226
Cyclone_Outlet_Gas_draft  14226   1962   4.84     89
Cyclone_cone_draft        14226   1538  -0.57    168
Cyclone_Gas_Outlet_Temp   14226   2525  30.02     66
Cyclone_Inlet_Draft       14226   1649  -1.34    141

In [66]:
zero_times = df.loc[
    sensor_data["Cyclone_Material_Temp"] == 0,
    "time"
]
zero_diff = zero_times.diff()
print(zero_diff.value_counts().head(10))

time
0 days 00:05:00     5906
0 days 00:10:00       52
0 days 00:15:00       12
0 days 00:20:00        4
0 days 00:25:00        3
9 days 09:20:00        1
26 days 21:35:00       1
1 days 01:40:00        1
4 days 05:35:00        1
1 days 00:05:00        1
Name: count, dtype: int64

In [67]:
print(zero_times.head(20))
print()
print(zero_times.tail(20))

5297                    NaT
5298                    NaT
5299                    NaT
5300                    NaT
5301                    NaT
15828                   NaT
17079   2017-03-01 07:15:00
19783   2017-03-10 16:35:00
19784   2017-03-10 16:40:00
19785   2017-03-10 16:45:00
25680                   NaT
25681                   NaT
58506                   NaT
58507                   NaT
58509                   NaT
58510                   NaT
63056   2017-08-07 22:40:00
70803   2017-09-03 20:15:00
71111   2017-09-04 21:55:00
72330   2017-09-09 03:30:00
Name: time, dtype: datetime64[us]

295087   NaT
295088   NaT
295089   NaT
295090   NaT
295091   NaT
295092   NaT
295093   NaT
295094   NaT
295095   NaT
295096   NaT
295097   NaT
295098   NaT
295099   NaT
295100   NaT
295101   NaT
371722   NaT
371723   NaT
371725   NaT
371726   NaT
371727   NaT
Name: time, dtype: datetime64[us]

In [68]:
material_zero = sensor_data["Cyclone_Material_Temp"] == 0 #cleanly separate the timestamp issue

print("Material temp zero rows:", material_zero.sum())
print(
    "Zero rows with invalid time:",
    df.loc[material_zero, "time"].isna().sum()
)

Material temp zero rows: 14226
Zero rows with invalid time: 8221

In [69]:
zero_times = df.loc[
    material_zero & df["time"].notna(),
    "time"
]
print("Valid zero timestamps:", len(zero_times))
print("First:", zero_times.min())
print("Last:", zero_times.max())

Valid zero timestamps: 6005
First: 2017-03-01 07:15:00
Last: 2019-10-12 23:55:00

In [70]:
material_negative = sensor_data["Cyclone_Material_Temp"] < 0
print("Negative material temperature:", material_negative.sum())
print(
    df.loc[
        material_negative,
        ["time"] + sensor_cols
    ].sort_values("time").head(20)
)

Negative material temperature: 84
                      time Cyclone_Inlet_Gas_Temp Cyclone_Material_Temp  \
45821  2017-06-09 02:25:00                 707.16                 -96.3
61368  2017-08-02 02:00:00                 887.59                  -185
73191  2017-09-12 03:15:00                 895.72               -165.18
73231  2017-09-12 06:35:00                 914.41                  -185
88033  2017-11-02 16:05:00                 885.44               -181.34
88034  2017-11-02 16:10:00                 893.35               -165.07
88035  2017-11-02 16:15:00                 874.57               -146.74
88036  2017-11-02 16:20:00                 892.09                  -185
88038  2017-11-02 16:30:00                 883.77                  -185
89123  2017-11-06 10:55:00                 920.21               -140.15
89126  2017-11-06 11:10:00                 933.02                  -185
89127  2017-11-06 11:15:00                 880.18                  -185
89129  2017-11-06 11:25:00                 936.74               -103.61
89130  2017-11-06 11:30:00                 910.45               -157.55
89134  2017-11-06 11:50:00                 866.94               -184.22
89135  2017-11-06 11:55:00                 874.92               -163.46
89138  2017-11-06 12:10:00                  886.7                 -2.81
124865 2018-03-11 13:20:00                 888.93                  -185
142684 2018-05-12 10:15:00                 897.81                 -12.5
157784 2018-07-03 20:35:00                  916.6               -168.55

       Cyclone_Outlet_Gas_draft Cyclone_cone_draft Cyclone_Gas_Outlet_Temp  \
45821                    -88.37            -116.07                  637.45
61368                   -224.07            -235.75                  891.56
73191                   -187.74            -204.91                  853.89
73231                   -171.56            -180.51                  904.65
88033                   -233.73            -189.41                  899.52
88034                   -233.22            -184.14                   899.8
88035                   -237.06            -182.74                  895.65
88036                   -239.51            -186.69                   895.2
88038                   -237.31            -188.79                  893.76
89123                   -195.59            -196.61                  866.26
89126                   -199.26            -195.53                  906.29
89127                   -211.43            -213.97                  895.78
89129                   -224.19             -219.4                  889.08
89130                   -222.81               -225                   898.4
89134                    -230.8            -235.95                  892.16
89135                    -229.2            -230.61                  873.52
89138                   -218.27            -222.74                  874.44
124865                  -254.53            -250.43                  720.64
142684                  -273.59            -255.79                  888.02
157784                  -292.29            -275.23                   933.2

       Cyclone_Inlet_Draft
45821               -74.02
61368               -177.3
73191              -162.17
73231              -152.89
88033              -194.43
88034              -194.92
88035              -197.89
88036              -200.22
88038              -193.84
89123              -171.33
89126              -180.21
89127              -186.02
89129              -194.39
89130              -199.71
89134               -210.2
89135              -203.02
89138              -192.96
124865             -204.21
142684              -218.9
157784             -215.24

In [71]:
print(
    sensor_data.loc[
        material_negative,
        "Cyclone_Material_Temp"
    ].describe()
)

count     84.00000
mean    -155.62619
std       52.41940
min     -185.00000
25%     -185.00000
50%     -185.00000
75%     -158.11250
max       -2.81000
Name: Cyclone_Material_Temp, dtype: float64

In [72]:
print(
    df.loc[
        material_negative,
        "time"
    ].sort_values().to_list()
)

[Timestamp('2017-06-09 02:25:00'), Timestamp('2017-08-02 02:00:00'), Timestamp('2017-09-12 03:15:00'), Timestamp('2017-09-12 06:35:00'), Timestamp('2017-11-02 16:05:00'), Timestamp('2017-11-02 16:10:00'), Timestamp('2017-11-02 16:15:00'), Timestamp('2017-11-02 16:20:00'), Timestamp('2017-11-02 16:30:00'), Timestamp('2017-11-06 10:55:00'), Timestamp('2017-11-06 11:10:00'), Timestamp('2017-11-06 11:15:00'), Timestamp('2017-11-06 11:25:00'), Timestamp('2017-11-06 11:30:00'), Timestamp('2017-11-06 11:50:00'), Timestamp('2017-11-06 11:55:00'), Timestamp('2017-11-06 12:10:00'), Timestamp('2018-03-11 13:20:00'), Timestamp('2018-05-12 10:15:00'), Timestamp('2018-07-03 20:35:00'), Timestamp('2018-09-02 22:20:00'), Timestamp('2018-09-02 22:30:00'), Timestamp('2018-09-02 22:35:00'), Timestamp('2019-04-01 04:55:00'), Timestamp('2019-09-08 17:20:00'), Timestamp('2019-09-08 18:50:00'), NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT]

In [73]:
negative_material = sensor_data["Cyclone_Material_Temp"] < 0
negative_valid_time = negative_material & df["time"].notna()
print("Total negative:", negative_material.sum())
print("Negative with valid time:", negative_valid_time.sum())
print("Negative with invalid time:", (negative_material & df["time"].isna()).sum())

Total negative: 84
Negative with valid time: 26
Negative with invalid time: 58

In [74]:
print(
    df.loc[
        negative_valid_time,
        ["time"] + sensor_cols
    ].sort_values("time")
)

                      time Cyclone_Inlet_Gas_Temp Cyclone_Material_Temp  \
45821  2017-06-09 02:25:00                 707.16                 -96.3
61368  2017-08-02 02:00:00                 887.59                  -185
73191  2017-09-12 03:15:00                 895.72               -165.18
73231  2017-09-12 06:35:00                 914.41                  -185
88033  2017-11-02 16:05:00                 885.44               -181.34
88034  2017-11-02 16:10:00                 893.35               -165.07
88035  2017-11-02 16:15:00                 874.57               -146.74
88036  2017-11-02 16:20:00                 892.09                  -185
88038  2017-11-02 16:30:00                 883.77                  -185
89123  2017-11-06 10:55:00                 920.21               -140.15
89126  2017-11-06 11:10:00                 933.02                  -185
89127  2017-11-06 11:15:00                 880.18                  -185
89129  2017-11-06 11:25:00                 936.74               -103.61
89130  2017-11-06 11:30:00                 910.45               -157.55
89134  2017-11-06 11:50:00                 866.94               -184.22
89135  2017-11-06 11:55:00                 874.92               -163.46
89138  2017-11-06 12:10:00                  886.7                 -2.81
124865 2018-03-11 13:20:00                 888.93                  -185
142684 2018-05-12 10:15:00                 897.81                 -12.5
157784 2018-07-03 20:35:00                  916.6               -168.55
175373 2018-09-02 22:20:00                 583.17               -123.76
175375 2018-09-02 22:30:00                 605.88               -176.41
175376 2018-09-02 22:35:00                 679.57                  -185
235645 2019-04-01 04:55:00                 872.64                -48.98
281874 2019-09-08 17:20:00                 905.42                  -185
281892 2019-09-08 18:50:00                 895.72                  -185

       Cyclone_Outlet_Gas_draft Cyclone_cone_draft Cyclone_Gas_Outlet_Temp  \
45821                    -88.37            -116.07                  637.45
61368                   -224.07            -235.75                  891.56
73191                   -187.74            -204.91                  853.89
73231                   -171.56            -180.51                  904.65
88033                   -233.73            -189.41                  899.52
88034                   -233.22            -184.14                   899.8
88035                   -237.06            -182.74                  895.65
88036                   -239.51            -186.69                   895.2
88038                   -237.31            -188.79                  893.76
89123                   -195.59            -196.61                  866.26
89126                   -199.26            -195.53                  906.29
89127                   -211.43            -213.97                  895.78
89129                   -224.19             -219.4                  889.08
89130                   -222.81               -225                   898.4
89134                    -230.8            -235.95                  892.16
89135                    -229.2            -230.61                  873.52
89138                   -218.27            -222.74                  874.44
124865                  -254.53            -250.43                  720.64
142684                  -273.59            -255.79                  888.02
157784                  -292.29            -275.23                   933.2
175373                     3.12             -11.61                  582.06
175375                   -24.54             -48.56                  605.58
175376                   -33.79             -59.27                  651.83
235645                  -264.55            -243.03                  881.67
281874                  -238.87            -194.43                  904.64
281892                  -252.86            -204.46                  890.61

       Cyclone_Inlet_Draft
45821               -74.02
61368               -177.3
73191              -162.17
73231              -152.89
88033              -194.43
88034              -194.92
88035              -197.89
88036              -200.22
88038              -193.84
89123              -171.33
89126              -180.21
89127              -186.02
89129              -194.39
89130              -199.71
89134               -210.2
89135              -203.02
89138              -192.96
124865             -204.21
142684              -218.9
157784             -215.24
175373                6.44
175375              -26.16
175376              -32.08
235645             -200.62
281874             -181.37
281892             -187.22

In [75]:
corr = sensor_data.corr()
print(corr.round(2))

                          Cyclone_Inlet_Gas_Temp  Cyclone_Material_Temp  \
Cyclone_Inlet_Gas_Temp                      1.00                   0.96
Cyclone_Material_Temp                       0.96                   1.00
Cyclone_Outlet_Gas_draft                   -0.90                  -0.88
Cyclone_cone_draft                         -0.90                  -0.88
Cyclone_Gas_Outlet_Temp                     0.99                   0.96
Cyclone_Inlet_Draft                        -0.90                  -0.88

                          Cyclone_Outlet_Gas_draft  Cyclone_cone_draft  \
Cyclone_Inlet_Gas_Temp                       -0.90               -0.90
Cyclone_Material_Temp                        -0.88               -0.88
Cyclone_Outlet_Gas_draft                      1.00                0.97
Cyclone_cone_draft                            0.97                1.00
Cyclone_Gas_Outlet_Temp                      -0.90               -0.89
Cyclone_Inlet_Draft                           1.00                0.97

                          Cyclone_Gas_Outlet_Temp  Cyclone_Inlet_Draft
Cyclone_Inlet_Gas_Temp                       0.99                -0.90
Cyclone_Material_Temp                        0.96                -0.88
Cyclone_Outlet_Gas_draft                    -0.90                 1.00
Cyclone_cone_draft                          -0.89                 0.97
Cyclone_Gas_Outlet_Temp                      1.00                -0.90
Cyclone_Inlet_Draft                         -0.90                 1.00

In [76]:
print(
    corr.abs()
        .where(~np.eye(len(corr), dtype=bool))
        .stack()
        .sort_values(ascending=False)
        .head(10)
)

Cyclone_Inlet_Draft       Cyclone_Outlet_Gas_draft    0.995442
Cyclone_Outlet_Gas_draft  Cyclone_Inlet_Draft         0.995442
Cyclone_Inlet_Gas_Temp    Cyclone_Gas_Outlet_Temp     0.990970
Cyclone_Gas_Outlet_Temp   Cyclone_Inlet_Gas_Temp      0.990970
Cyclone_cone_draft        Cyclone_Inlet_Draft         0.969447
Cyclone_Inlet_Draft       Cyclone_cone_draft          0.969447
Cyclone_cone_draft        Cyclone_Outlet_Gas_draft    0.968425
Cyclone_Outlet_Gas_draft  Cyclone_cone_draft          0.968425
Cyclone_Material_Temp     Cyclone_Inlet_Gas_Temp      0.964728
Cyclone_Inlet_Gas_Temp    Cyclone_Material_Temp       0.964728
dtype: float64

In [77]:
print(sensor_data.quantile([0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]).T)

                              0.01    0.05      0.25     0.50    0.75    0.95  \
Cyclone_Inlet_Gas_Temp     23.5300   30.19  856.2700  882.380  901.11  934.07
Cyclone_Material_Temp       0.0000   20.43  867.6675  913.360  943.66  985.81
Cyclone_Outlet_Gas_draft -296.6300 -277.61 -247.1900 -215.260 -170.13    4.68
Cyclone_cone_draft       -278.1600 -258.80 -226.7700 -198.560 -143.64    0.33
Cyclone_Gas_Outlet_Temp    23.8500   30.24  801.9600  871.525  899.30  933.05
Cyclone_Inlet_Draft      -236.8304 -221.12 -193.5100 -169.460 -136.29    0.85

                               0.99
Cyclone_Inlet_Gas_Temp     969.8602
Cyclone_Material_Temp     1017.8973
Cyclone_Outlet_Gas_draft    13.3503
Cyclone_cone_draft           1.8200
Cyclone_Gas_Outlet_Temp    961.8603
Cyclone_Inlet_Draft         13.8104

In [78]:
print(
    sensor_data[
        ["Cyclone_Inlet_Gas_Temp",
         "Cyclone_Gas_Outlet_Temp",
         "Cyclone_Inlet_Draft"]
    ].describe()
)

       Cyclone_Inlet_Gas_Temp  Cyclone_Gas_Outlet_Temp  Cyclone_Inlet_Draft
count           376399.000000            376398.000000        376397.000000
mean               727.348549               715.759972          -141.302857
std                328.664814               325.346446            77.615576
min                  0.000000                13.790000          -396.370000
25%                856.270000               801.960000          -193.510000
50%                882.380000               871.525000          -169.460000
75%                901.110000               899.300000          -136.290000
max               1157.630000              1375.000000            41.640000

In [79]:
for threshold in [100, 300, 500, 700, 800]:
    count = (sensor_data["Cyclone_Inlet_Gas_Temp"] < threshold).sum()
    pct = count / len(sensor_data) * 100
    print(f"< {threshold}: {count:,} rows ({pct:.2f}%)")

< 100: 61,814 rows (16.37%)
< 300: 68,686 rows (18.18%)
< 500: 74,092 rows (19.62%)
< 700: 79,143 rows (20.95%)
< 800: 81,308 rows (21.53%)

In [80]:
low_temp = sensor_data["Cyclone_Inlet_Gas_Temp"] < 700
print(
    df.loc[
        low_temp,
        ["time"] + sensor_cols
    ].head(20)
)

     time Cyclone_Inlet_Gas_Temp Cyclone_Material_Temp  \
6368  NaT                  686.8                519.25
6369  NaT                 643.16                490.98
6370  NaT                 613.86                470.67
6371  NaT                 593.11                440.77
6372  NaT                 598.86                459.13
6373  NaT                 592.82                463.82
6374  NaT                 571.57                424.36
6375  NaT                 550.68                400.93
6376  NaT                 547.85                404.06
6377  NaT                 556.42                426.91
6378  NaT                  548.3                420.73
6379  NaT                 532.63                393.36
6380  NaT                 521.99                385.99
6381  NaT                 515.07                375.29
6382  NaT                  510.8                373.24
6383  NaT                 500.46                350.45
6384  NaT                 488.02                335.71
6385  NaT                 481.73                325.87
6386  NaT                 492.42                356.42
6387  NaT                 486.41                354.17

     Cyclone_Outlet_Gas_draft Cyclone_cone_draft Cyclone_Gas_Outlet_Temp  \
6368                    -8.24             -25.09                  673.64
6369                    -9.93             -27.09                  635.41
6370                    -8.33             -25.91                   609.7
6371                    -6.92             -23.36                  587.92
6372                    -7.29             -24.19                  581.08
6373                     -8.8             -24.96                  579.13
6374                   -10.39             -23.81                  561.75
6375                    -6.38             -21.31                  543.31
6376                     -8.9             -21.52                  533.75
6377                    -6.72             -20.77                  537.94
6378                    -7.21             -21.76                  535.34
6379                   -14.97             -30.54                  522.49
6380                    -7.26             -20.46                  512.11
6381                    -7.11             -22.47                  501.59
6382                    -6.02             -21.12                  498.51
6383                    -6.44             -23.78                  487.17
6384                    -6.99             -22.18                   475.9
6385                   -10.26             -25.06                  465.56
6386                     -7.7             -21.83                  472.95
6387                    -9.23             -23.09                  470.53

     Cyclone_Inlet_Draft
6368               -7.34
6369               -7.75
6370               -7.42
6371               -6.88
6372               -7.24
6373               -6.91
6374               -7.27
6375                -4.6
6376               -4.84
6377               -6.62
6378               -5.43
6379              -14.29
6380               -6.55
6381               -6.46
6382               -5.74
6383               -8.31
6384               -8.83
6385               -7.15
6386               -5.36
6387               -9.04

In [81]:
low_temp = sensor_data["Cyclone_Inlet_Gas_Temp"] < 700
print("Total low-temp rows:", low_temp.sum())
print(
    "Low-temp rows with valid time:",
    (low_temp & df["time"].notna()).sum()
)
print(
    "Low-temp rows with invalid time:",
    (low_temp & df["time"].isna()).sum()
)

Total low-temp rows: 79143
Low-temp rows with valid time: 34042
Low-temp rows with invalid time: 45101

In [82]:
low_temp_valid = low_temp & df["time"].notna()
print(
    df.loc[
        low_temp_valid,
        ["time"] + sensor_cols
    ].sort_values("time").head(20)
)

                     time Cyclone_Inlet_Gas_Temp Cyclone_Material_Temp  \
17338 2017-03-02 04:50:00                 672.88                558.39
17339 2017-03-02 04:55:00                 647.14                 531.4
17340 2017-03-02 05:00:00                 631.57                508.75
17341 2017-03-02 05:05:00                  618.5                505.44
17342 2017-03-02 05:10:00                 605.83                484.44
17343 2017-03-02 05:15:00                  601.2                542.98
17344 2017-03-02 05:20:00                  602.2                520.71
17345 2017-03-02 05:25:00                 591.47                502.17
17346 2017-03-02 05:30:00                 580.23                488.67
17347 2017-03-02 05:35:00                 569.84                477.61
17348 2017-03-02 05:40:00                 559.48                 460.3
17349 2017-03-02 05:45:00                 549.95                444.57
17350 2017-03-02 05:50:00                 541.88                436.22
17351 2017-03-02 05:55:00                 535.27                452.45
17352 2017-03-02 06:00:00                 557.12                498.42
17353 2017-03-02 06:05:00                 579.81                451.27
17354 2017-03-02 06:10:00                 582.31                467.05
17355 2017-03-02 06:15:00                 598.19                436.55
17356 2017-03-02 06:20:00                 601.24                412.82
17357 2017-03-02 06:25:00                 605.53                489.73

      Cyclone_Outlet_Gas_draft Cyclone_cone_draft Cyclone_Gas_Outlet_Temp  \
17338                    -0.28             -19.38                  702.81
17339                     0.31             -17.91                  682.32
17340                    -1.35             -18.33                  663.16
17341                    -1.67             -19.93                  646.01
17342                    -1.55             -19.01                  632.46
17343                    -0.53             -18.01                     623
17344                    -0.49             -17.83                  620.97
17345                    -2.95             -20.19                  614.83
17346                    -4.13             -21.11                   606.4
17347                    -3.33             -19.76                   597.9
17348                    -2.97             -20.04                  589.05
17349                    -0.77             -17.93                  580.54
17350                    -4.47             -19.91                  571.88
17351                    -1.94             -18.23                  562.57
17352                    12.45              -7.37                  561.88
17353                     8.59             -12.27                  571.57
17354                    10.29              -10.8                  575.75
17355                    12.78              -6.22                  584.43
17356                    10.53              -9.05                  588.58
17357                    13.27               -6.8                  592.11

      Cyclone_Inlet_Draft
17338               -2.99
17339               -2.92
17340               -3.27
17341               -4.75
17342                -2.4
17343               -1.03
17344               -3.88
17345               -4.76
17346               -7.42
17347               -6.21
17348               -3.88
17349               -4.12
17350               -5.34
17351               -3.28
17352                7.13
17353                2.08
17354                 4.6
17355                7.59
17356                3.86
17357                8.23

In [83]:
low_temp_valid = low_temp & df["time"].notna()

print(
    df.loc[
        low_temp_valid,
        ["time"] + sensor_cols
    ].sort_values("time").head(20)
)

                     time Cyclone_Inlet_Gas_Temp Cyclone_Material_Temp  \
17338 2017-03-02 04:50:00                 672.88                558.39
17339 2017-03-02 04:55:00                 647.14                 531.4
17340 2017-03-02 05:00:00                 631.57                508.75
17341 2017-03-02 05:05:00                  618.5                505.44
17342 2017-03-02 05:10:00                 605.83                484.44
17343 2017-03-02 05:15:00                  601.2                542.98
17344 2017-03-02 05:20:00                  602.2                520.71
17345 2017-03-02 05:25:00                 591.47                502.17
17346 2017-03-02 05:30:00                 580.23                488.67
17347 2017-03-02 05:35:00                 569.84                477.61
17348 2017-03-02 05:40:00                 559.48                 460.3
17349 2017-03-02 05:45:00                 549.95                444.57
17350 2017-03-02 05:50:00                 541.88                436.22
17351 2017-03-02 05:55:00                 535.27                452.45
17352 2017-03-02 06:00:00                 557.12                498.42
17353 2017-03-02 06:05:00                 579.81                451.27
17354 2017-03-02 06:10:00                 582.31                467.05
17355 2017-03-02 06:15:00                 598.19                436.55
17356 2017-03-02 06:20:00                 601.24                412.82
17357 2017-03-02 06:25:00                 605.53                489.73

      Cyclone_Outlet_Gas_draft Cyclone_cone_draft Cyclone_Gas_Outlet_Temp  \
17338                    -0.28             -19.38                  702.81
17339                     0.31             -17.91                  682.32
17340                    -1.35             -18.33                  663.16
17341                    -1.67             -19.93                  646.01
17342                    -1.55             -19.01                  632.46
17343                    -0.53             -18.01                     623
17344                    -0.49             -17.83                  620.97
17345                    -2.95             -20.19                  614.83
17346                    -4.13             -21.11                   606.4
17347                    -3.33             -19.76                   597.9
17348                    -2.97             -20.04                  589.05
17349                    -0.77             -17.93                  580.54
17350                    -4.47             -19.91                  571.88
17351                    -1.94             -18.23                  562.57
17352                    12.45              -7.37                  561.88
17353                     8.59             -12.27                  571.57
17354                    10.29              -10.8                  575.75
17355                    12.78              -6.22                  584.43
17356                    10.53              -9.05                  588.58
17357                    13.27               -6.8                  592.11

      Cyclone_Inlet_Draft
17338               -2.99
17339               -2.92
17340               -3.27
17341               -4.75
17342                -2.4
17343               -1.03
17344               -3.88
17345               -4.76
17346               -7.42
17347               -6.21
17348               -3.88
17349               -4.12
17350               -5.34
17351               -3.28
17352                7.13
17353                2.08
17354                 4.6
17355                7.59
17356                3.86
17357                8.23

In [84]:
valid_low_times = df.loc[low_temp_valid, "time"]

print("First valid low-temp time:", valid_low_times.min())
print("Last valid low-temp time:", valid_low_times.max())

First valid low-temp time: 2017-03-02 04:50:00
Last valid low-temp time: 2020-05-02 13:05:00

In [85]:
low = (
    sensor_data["Cyclone_Inlet_Gas_Temp"] < 700
) & df["time"].notna()

run_id = low.ne(low.shift()).cumsum()

runs = (
    df.loc[low]
      .assign(run_id=run_id[low].values)
      .groupby("run_id")
      .agg(
          start=("time", "min"),
          end=("time", "max"),
          rows=("time", "size")
      )
)

runs["duration"] = runs["end"] - runs["start"]

print(runs.sort_values("duration", ascending=False).head(15))

                     start                 end  rows         duration
run_id
98     2019-10-01 00:00:00 2019-10-12 23:55:00  3456 11 days 23:55:00
110    2020-04-01 00:00:00 2020-04-12 23:55:00  3456 11 days 23:55:00
64     2018-10-01 00:00:00 2018-10-12 23:55:00  3456 11 days 23:55:00
96     2019-08-01 16:50:00 2019-08-12 23:55:00  3254 11 days 07:05:00
92     2019-06-03 04:05:00 2019-06-12 23:55:00  2831  9 days 19:50:00
32     2017-12-01 00:00:00 2017-12-08 20:55:00  2268  7 days 20:55:00
104    2019-12-01 00:00:00 2019-12-07 12:35:00  1880  6 days 12:35:00
56     2018-07-04 21:30:00 2018-07-09 13:00:00  1339  4 days 15:30:00
106    2019-12-07 12:45:00 2019-12-11 09:15:00  1111  3 days 20:30:00
80     2019-03-09 06:40:00 2019-03-12 23:55:00  1072  3 days 17:15:00
86     2019-05-05 02:45:00 2019-05-08 17:55:00  1047  3 days 15:10:00
90     2019-05-09 16:20:00 2019-05-12 23:55:00   956  3 days 07:35:00
16     2017-10-06 08:30:00 2017-10-09 16:00:00   955  3 days 07:30:00
42     2018-04-01 17:00:00 2018-04-04 03:35:00   704  2 days 10:35:00
12     2017-10-01 00:00:00 2017-10-03 09:55:00   696  2 days 09:55:00

In [86]:
# Take the largest 5 low-temperature runs
top_runs = runs.sort_values("duration", ascending=False).head(5)
for run_id in top_runs.index:
    start = top_runs.loc[run_id, "start"]
    end = top_runs.loc[run_id, "end"]

    period = sensor_data[
        (df["time"] >= start) &
        (df["time"] <= end)
    ]

    print("\n" + "=" * 70)
    print(f"Run {run_id}: {start} -> {end}")
    print("=" * 70)

    print(
        period[
            [
                "Cyclone_Inlet_Gas_Temp",
                "Cyclone_Material_Temp",
                "Cyclone_Gas_Outlet_Temp",
                "Cyclone_Outlet_Gas_draft",
                "Cyclone_cone_draft",
                "Cyclone_Inlet_Draft"
            ]
        ].describe().loc[["mean", "min", "50%", "max"]]
    )

======================================================================
Run 98: 2019-10-01 00:00:00 -> 2019-10-12 23:55:00
======================================================================
      Cyclone_Inlet_Gas_Temp  Cyclone_Material_Temp  Cyclone_Gas_Outlet_Temp  \
mean                29.24151               4.121954                29.601924
min                 25.40000               0.000000                25.690000
50%                 29.25000               0.000000                29.750000
max                 35.54000             900.000000                35.600000

      Cyclone_Outlet_Gas_draft  Cyclone_cone_draft  Cyclone_Inlet_Draft
mean                  0.266308           -1.540871            -3.019152
min                 -35.990000          -39.220000           -37.700000
50%                   1.460000           -0.380000            -1.920000
max                   6.150000            0.870000             3.380000

======================================================================
Run 110: 2020-04-01 00:00:00 -> 2020-04-12 23:55:00
======================================================================
      Cyclone_Inlet_Gas_Temp  Cyclone_Material_Temp  Cyclone_Gas_Outlet_Temp  \
mean               31.843339              45.271514                31.555237
min                30.000000              27.520000                29.870000
50%                31.880000              30.970000                31.610000
max                34.060000             900.000000                33.590000

      Cyclone_Outlet_Gas_draft  Cyclone_cone_draft  Cyclone_Inlet_Draft
mean                  0.861884            1.510003             0.775165
min                  -3.330000            0.530000            -1.460000
50%                   0.850000            1.530000             0.820000
max                   3.900000            2.050000             1.650000

======================================================================
Run 64: 2018-10-01 00:00:00 -> 2018-10-12 23:55:00
======================================================================
      Cyclone_Inlet_Gas_Temp  Cyclone_Material_Temp  Cyclone_Gas_Outlet_Temp  \
mean               32.535269               60.08711                32.816418
min                27.930000               26.37000                28.730000
50%                32.530000               30.15000                32.860000
max                38.740000              900.00000                38.920000

      Cyclone_Outlet_Gas_draft  Cyclone_cone_draft  Cyclone_Inlet_Draft
mean                  1.638819           -0.297086            -1.666753
min                   1.000000           -1.250000            -3.310000
50%                   1.630000           -0.200000            -1.660000
max                   3.520000            0.540000            -0.270000

======================================================================
Run 96: 2019-08-01 16:50:00 -> 2019-08-12 23:55:00
======================================================================
      Cyclone_Inlet_Gas_Temp  Cyclone_Material_Temp  Cyclone_Gas_Outlet_Temp  \
mean               56.974733              70.418853                58.188132
min                27.590000              59.560000                27.530000
50%                30.810000              59.560000                30.910000
max               699.390000             815.080000               727.150000

      Cyclone_Outlet_Gas_draft  Cyclone_cone_draft  Cyclone_Inlet_Draft
mean                 -7.985418           -8.962022            -9.120793
min                 -90.630000          -82.640000           -75.910000
50%                  -3.730000           -4.655000            -6.105000
max                  24.820000            9.210000            27.770000

======================================================================
Run 92: 2019-06-03 04:05:00 -> 2019-06-12 23:55:00
======================================================================
      Cyclone_Inlet_Gas_Temp  Cyclone_Material_Temp  Cyclone_Gas_Outlet_Temp  \
mean               67.122854              65.259484                66.665288
min                36.470000              10.800000                36.230000
50%                43.530000              41.640000                42.580000
max               699.350000             900.000000               703.750000

      Cyclone_Outlet_Gas_draft  Cyclone_cone_draft  Cyclone_Inlet_Draft
mean                 -1.257436           -4.840208             -3.54402
min                 -56.760000          -57.090000            -49.90000
50%                   2.160000           -0.990000             -1.19000
max                  17.950000            1.720000             20.66000

In [87]:
material = sensor_data["Cyclone_Material_Temp"]

for value in [0, 900]:
    mask = material == value

    print("\n" + "=" * 60)
    print(f"Material Temperature = {value}")
    print("=" * 60)

    print("Total rows:", mask.sum())

    valid = df.loc[mask & df["time"].notna(), "time"]

    print("Rows with valid timestamps:", len(valid))

    if len(valid) > 0:
        print("First:", valid.min())
        print("Last :", valid.max())

    print("\nOther sensor medians:")
    print(
        sensor_data.loc[mask, [
            "Cyclone_Inlet_Gas_Temp",
            "Cyclone_Gas_Outlet_Temp",
            "Cyclone_Outlet_Gas_draft",
            "Cyclone_cone_draft",
            "Cyclone_Inlet_Draft"
        ]].median()
    )

============================================================
Material Temperature = 0
============================================================
Total rows: 14226
Rows with valid timestamps: 6005
First: 2017-03-01 07:15:00
Last : 2019-10-12 23:55:00

Other sensor medians:
Cyclone_Inlet_Gas_Temp      31.225
Cyclone_Gas_Outlet_Temp     31.500
Cyclone_Outlet_Gas_draft     2.145
Cyclone_cone_draft          -0.440
Cyclone_Inlet_Draft         -1.650
dtype: float64

============================================================
Material Temperature = 900
============================================================
Total rows: 2671
Rows with valid timestamps: 600
First: 2017-03-01 02:30:00
Last : 2020-08-06 10:30:00

Other sensor medians:
Cyclone_Inlet_Gas_Temp      869.28
Cyclone_Gas_Outlet_Temp     858.97
Cyclone_Outlet_Gas_draft   -203.81
Cyclone_cone_draft         -189.02
Cyclone_Inlet_Draft        -170.36
dtype: float64

In [88]:
# Look at the original time values that became NaT
nat_rows = df[df["time"].isna()]

print("NaT rows:", len(nat_rows))

print(
    nat_rows["time"]
    .head(20)
)

NaT rows: 227235
3456   NaT
3457   NaT
3458   NaT
3459   NaT
3460   NaT
3461   NaT
3462   NaT
3463   NaT
3464   NaT
3465   NaT
3466   NaT
3467   NaT
3468   NaT
3469   NaT
3470   NaT
3471   NaT
3472   NaT
3473   NaT
3474   NaT
3475   NaT
Name: time, dtype: datetime64[us]

In [90]:
raw_df = pd.read_csv("cyclone_data.csv")

print(raw_df["time"].head(10))
print(raw_df["time"].iloc[3445:3465])

0    01-01-2017 00:00
1    01-01-2017 00:05
2    01-01-2017 00:10
3    01-01-2017 00:15
4    01-01-2017 00:20
5    01-01-2017 00:25
6    01-01-2017 00:30
7    01-01-2017 00:35
8    01-01-2017 00:40
9    01-01-2017 00:45
Name: time, dtype: str
3445    01-12-2017 23:05
3446    01-12-2017 23:10
3447    01-12-2017 23:15
3448    01-12-2017 23:20
3449    01-12-2017 23:25
3450    01-12-2017 23:30
3451    01-12-2017 23:35
3452    01-12-2017 23:40
3453    01-12-2017 23:45
3454    01-12-2017 23:50
3455    01-12-2017 23:55
3456      1/13/2017 0:00
3457      1/13/2017 0:05
3458      1/13/2017 0:10
3459      1/13/2017 0:15
3460      1/13/2017 0:20
3461      1/13/2017 0:25
3462      1/13/2017 0:30
3463      1/13/2017 0:35
3464      1/13/2017 0:40
Name: time, dtype: str

In [91]:
print(raw_df["time"].iloc[0])
print(raw_df["time"].iloc[3455])
print(raw_df["time"].iloc[3456])
print(raw_df["time"].iloc[3457])

print("\nLast few:")
print(raw_df["time"].tail())

01-01-2017 00:00
01-12-2017 23:55
1/13/2017 0:00
1/13/2017 0:05

Last few:
377714    08-07-2020 11:55
377715    08-07-2020 12:00
377716    08-07-2020 12:05
377717    08-07-2020 12:10
377718    08-07-2020 12:15
Name: time, dtype: str

In [92]:
raw_df = pd.read_csv("cyclone_data.csv")

raw_df["time_parsed"] = pd.to_datetime(
    raw_df["time"],
    format="mixed",
    errors="coerce"
)
print(raw_df[["time", "time_parsed"]].head())
print(raw_df[["time", "time_parsed"]].iloc[3450:3465])
print(raw_df["time_parsed"].isna().sum())
print(raw_df["time_parsed"].min())
print(raw_df["time_parsed"].max())

               time         time_parsed
0  01-01-2017 00:00 2017-01-01 00:00:00
1  01-01-2017 00:05 2017-01-01 00:05:00
2  01-01-2017 00:10 2017-01-01 00:10:00
3  01-01-2017 00:15 2017-01-01 00:15:00
4  01-01-2017 00:20 2017-01-01 00:20:00
                  time         time_parsed
3450  01-12-2017 23:30 2017-01-12 23:30:00
3451  01-12-2017 23:35 2017-01-12 23:35:00
3452  01-12-2017 23:40 2017-01-12 23:40:00
3453  01-12-2017 23:45 2017-01-12 23:45:00
3454  01-12-2017 23:50 2017-01-12 23:50:00
3455  01-12-2017 23:55 2017-01-12 23:55:00
3456    1/13/2017 0:00 2017-01-13 00:00:00
3457    1/13/2017 0:05 2017-01-13 00:05:00
3458    1/13/2017 0:10 2017-01-13 00:10:00
3459    1/13/2017 0:15 2017-01-13 00:15:00
3460    1/13/2017 0:20 2017-01-13 00:20:00
3461    1/13/2017 0:25 2017-01-13 00:25:00
3462    1/13/2017 0:30 2017-01-13 00:30:00
3463    1/13/2017 0:35 2017-01-13 00:35:00
3464    1/13/2017 0:40 2017-01-13 00:40:00
0
2017-01-01 00:00:00
2020-08-07 12:15:00

In [93]:
df = raw_df.copy()
df["time"] = df["time_parsed"]
df = df.sort_values("time").reset_index(drop=True)
print(df["time"].isna().sum())
print(df["time"].min())
print(df["time"].max())

0
2017-01-01 00:00:00
2020-08-07 12:15:00

In [94]:
low = (
    sensor_data["Cyclone_Inlet_Gas_Temp"] < 700
)

run_id = low.ne(low.shift()).cumsum()

runs = (
    df.loc[low]
      .assign(run_id=run_id[low].values)
      .groupby("run_id")
      .agg(
          start=("time", "min"),
          end=("time", "max"),
          rows=("time", "size")
      )
)

runs["duration"] = runs["end"] - runs["start"]

print(
    runs
    .sort_values("duration", ascending=False)
    .head(20)
)

                     start                 end   rows         duration
run_id
272    2020-03-22 23:00:00 2020-05-01 23:55:00  11532 40 days 00:55:00
242    2019-09-14 08:20:00 2019-10-16 19:25:00   9350 32 days 11:05:00
162    2018-09-25 16:05:00 2018-10-15 13:05:00   5725 19 days 21:00:00
232    2019-06-03 04:05:00 2019-06-22 02:10:00   5450 18 days 22:05:00
264    2019-12-11 09:25:00 2019-12-24 20:05:00   3873 13 days 10:40:00
238    2019-08-01 16:50:00 2019-08-14 11:35:00   3682 12 days 18:45:00
48     2017-09-22 12:30:00 2017-10-03 09:55:00   3138 10 days 21:25:00
18     2017-05-20 15:25:00 2017-05-30 21:10:00   2950 10 days 05:45:00
88     2017-11-30 10:30:00 2017-12-08 20:55:00   2430  8 days 10:25:00
260    2019-11-29 13:00:00 2019-12-07 12:35:00   2300  7 days 23:35:00
250    2019-10-19 15:15:00 2019-10-26 07:35:00   1925  6 days 16:20:00
68     2017-10-13 16:50:00 2017-10-19 03:40:00   1571  5 days 10:50:00
156    2018-08-29 01:55:00 2018-09-02 22:35:00   1401  4 days 20:40:00
144    2018-07-04 21:30:00 2018-07-09 13:00:00   1339  4 days 15:30:00
226    2019-05-09 16:20:00 2019-05-14 03:15:00   1284  4 days 10:55:00
198    2019-03-09 06:40:00 2019-03-13 11:20:00   1209  4 days 04:40:00
10     2017-03-21 04:40:00 2017-03-25 03:35:00   1140  3 days 22:55:00
262    2019-12-07 12:45:00 2019-12-11 09:15:00   1111  3 days 20:30:00
222    2019-05-05 02:45:00 2019-05-08 17:55:00   1047  3 days 15:10:00
52     2017-10-06 08:30:00 2017-10-09 16:00:00    955  3 days 07:30:00

In [95]:
time_diff = df["time"].diff()

print(time_diff.value_counts().head(10))
print("\nLargest gaps:")
print(time_diff.sort_values(ascending=False).head(10))
print("\nDuplicate timestamps:", df["time"].duplicated().sum())

time
0 days 00:05:00    377715
1 days 00:00:00         3
Name: count, dtype: int64

Largest gaps:
104833   1 days 00:00:00
314499   1 days 00:00:00
209666   1 days 00:00:00
1        0 days 00:05:00
251810   0 days 00:05:00
251818   0 days 00:05:00
251817   0 days 00:05:00
251816   0 days 00:05:00
251815   0 days 00:05:00
251814   0 days 00:05:00
Name: time, dtype: timedelta64[us]

Duplicate timestamps: 0

In [96]:
# Combine timestamp + cleaned numeric sensor data
cleaned_data = pd.concat(
    [df[["time"]], sensor_data],
    axis=1
)
# Save to CSV
cleaned_data.to_csv(
    "cleaned_sensor_data.csv",
    index=False
)
print("Cleaned data saved successfully.")
print(cleaned_data.shape)
print(cleaned_data.head())

Cleaned data saved successfully.
(377719, 7)
                 time  Cyclone_Inlet_Gas_Temp  Cyclone_Material_Temp  \
0 2017-01-01 00:00:00                  867.63                 910.42
1 2017-01-01 00:05:00                  879.23                 918.14
2 2017-01-01 00:10:00                  875.67                 924.18
3 2017-01-01 00:15:00                  875.28                 923.15
4 2017-01-01 00:20:00                  891.66                 934.26

   Cyclone_Outlet_Gas_draft  Cyclone_cone_draft  Cyclone_Gas_Outlet_Temp  \
0                   -189.54             -186.04                   852.13
1                   -184.33             -182.10                   862.53
2                   -181.26             -166.47                   866.06
3                   -179.15             -174.83                   865.85
4                   -178.32             -173.72                   876.06

   Cyclone_Inlet_Draft
0              -145.90
1              -149.76
2              -145.01
3              -142.82
4              -143.39