In [6]:
import pandas as pd
import numpy as np

df = pd.read_csv(
    "feature_engineered_data.csv",
    parse_dates=["time"]
)
df = df.sort_values("time").reset_index(drop=True)
print("Shape:", df.shape)

Shape: (377719, 44)

In [7]:
sensor_cols = [
    "Cyclone_Inlet_Gas_Temp",
    "Cyclone_Gas_Outlet_Temp",
    "Cyclone_Outlet_Gas_draft",
    "Cyclone_cone_draft",
    "Cyclone_Inlet_Draft",
    "Cyclone_Material_Temp"
]

relationship_features = [
    "Temp_Inlet_Outlet_Diff",
    "Temp_Material_Inlet_Diff",
    "Temp_Material_Outlet_Diff",
    "Draft_Inlet_Outlet_Diff",
    "Draft_Cone_Inlet_Diff",
    "Draft_Cone_Outlet_Diff"
]

change_features = [
    col for col in df.columns
    if "_change_5min" in col
    or "_change_30min" in col
    or "_change_60min" in col
]

rolling_std_features = [
    col for col in df.columns
    if "_rolling_std_60min" in col
]

model_features = (
    sensor_cols
    + relationship_features
    + change_features
    + rolling_std_features
)

print("Number of model features:", len(model_features))

Number of model features: 36

In [8]:
sensor_cols = [
    "Cyclone_Inlet_Gas_Temp",
    "Cyclone_Gas_Outlet_Temp",
    "Cyclone_Outlet_Gas_draft",
    "Cyclone_cone_draft",
    "Cyclone_Inlet_Draft",
    "Cyclone_Material_Temp"
]

relationship_features = [
    "Temp_Inlet_Outlet_Diff",
    "Temp_Material_Inlet_Diff",
    "Temp_Material_Outlet_Diff",
    "Draft_Inlet_Outlet_Diff",
    "Draft_Cone_Inlet_Diff",
    "Draft_Cone_Outlet_Diff"
]

change_features = [
    col for col in df.columns
    if "_change_5min" in col
    or "_change_30min" in col
    or "_change_60min" in col
]

rolling_std_features = [
    col for col in df.columns
    if "_rolling_std_60min" in col
]

model_features = (
    sensor_cols
    + relationship_features
    + change_features
    + rolling_std_features
)

print("Number of model features:", len(model_features))

Number of model features: 36

In [9]:
model_data = df.dropna(subset=model_features).copy()

X = model_data[model_features]

print("Original rows:", len(df))
print("Modeling rows:", len(model_data))
print("Features:", X.shape[1])
print("Missing values:", X.isna().sum().sum())
print("Infinite values:", np.isinf(X).sum().sum())

Original rows: 377719
Modeling rows: 374761
Features: 36
Missing values: 0
Infinite values: 0

In [10]:
from sklearn.ensemble import IsolationForest

In [11]:
iso_model = IsolationForest(
    n_estimators=200,
    contamination="auto",
    random_state=42,
    n_jobs=-1
)

iso_model.fit(X)

print("Isolation Forest fitted successfully.")

Isolation Forest fitted successfully.

In [12]:
# Higher values from this score mean observations are more abnormal.
anomaly_score = -iso_model.score_samples(X)
print("Minimum score:", anomaly_score.min())
print("Maximum score:", anomaly_score.max())
print("Median score:", np.median(anomaly_score))

Minimum score: 0.3378433081847462
Maximum score: 0.7406175560827891
Median score: 0.3792851444011179

In [13]:
print(
    pd.Series(anomaly_score).describe(
        percentiles=[0.90, 0.95, 0.97, 0.98, 0.99, 0.995, 0.999]
    )
)

count    374761.000000
mean          0.394409
std           0.047201
min           0.337843
90%           0.448986
95%           0.485814
97%           0.519798
98%           0.547889
99%           0.597745
99.5%         0.637236
99.9%         0.685557
max           0.740618
dtype: float64

In [14]:
model_data["anomaly_score"] = anomaly_score
print(
    model_data[
        ["time", "anomaly_score"]
    ].sort_values("anomaly_score", ascending=False).head(20)
)

                      time  anomaly_score
199941 2018-11-27 05:40:00       0.740618
72351  2017-09-09 05:15:00       0.737177
199942 2018-11-27 05:45:00       0.728122
116791 2018-02-11 12:30:00       0.725777
199946 2018-11-27 06:05:00       0.725355
116793 2018-02-11 12:40:00       0.725066
116792 2018-02-11 12:35:00       0.724147
141844 2018-05-09 12:15:00       0.723763
148264 2018-05-31 19:15:00       0.723424
143966 2018-05-16 21:05:00       0.722930
199945 2018-11-27 06:00:00       0.722905
99625  2017-12-12 22:05:00       0.722345
199944 2018-11-27 05:55:00       0.722074
141843 2018-05-09 12:10:00       0.722027
143963 2018-05-16 20:50:00       0.720957
156184 2018-06-28 07:15:00       0.720677
143967 2018-05-16 21:10:00       0.720660
143964 2018-05-16 20:55:00       0.720127
143850 2018-05-16 11:25:00       0.719836
44258  2017-06-03 16:10:00       0.719391

In [15]:
thresholds = {
    "95th percentile": np.percentile(anomaly_score, 95),
    "97th percentile": np.percentile(anomaly_score, 97),
    "98th percentile": np.percentile(anomaly_score, 98),
    "99th percentile": np.percentile(anomaly_score, 99),
    "99.5th percentile": np.percentile(anomaly_score, 99.5),
    "99.9th percentile": np.percentile(anomaly_score, 99.9),
}

for name, threshold in thresholds.items():
    count = (anomaly_score >= threshold).sum()
    percentage = count / len(anomaly_score) * 100

    print(
        f"{name}: "
        f"threshold={threshold:.4f}, "
        f"observations={count}, "
        f"percentage={percentage:.2f}%"
    )

95th percentile: threshold=0.4858, observations=18739, percentage=5.00%
97th percentile: threshold=0.5198, observations=11243, percentage=3.00%
98th percentile: threshold=0.5479, observations=7496, percentage=2.00%
99th percentile: threshold=0.5977, observations=3748, percentage=1.00%
99.5th percentile: threshold=0.6372, observations=1874, percentage=0.50%
99.9th percentile: threshold=0.6856, observations=375, percentage=0.10%

testing persistence at several thresholds

In [16]:
# Add candidate anomaly flags
for name, threshold in thresholds.items():
    short_name = (
        name.replace("th percentile", "")
            .replace(".", "_")
            .replace("%", "")
    )
    model_data[f"anomaly_{short_name}"] = (
        model_data["anomaly_score"] >= threshold
    )

In [17]:

# Use the 99th percentile as the first candidate threshold
threshold_99 = thresholds["99th percentile"]
model_data["anomaly_99"] = (
    model_data["anomaly_score"] >= threshold_99
)

# Identify consecutive groups of anomalous/non-anomalous observations
model_data["anomaly_group"] = (
    model_data["anomaly_99"] != model_data["anomaly_99"].shift()
).cumsum()

groups_99 = (
    model_data[model_data["anomaly_99"]]
    .groupby("anomaly_group")
    .agg(
        start_time=("time", "min"),
        end_time=("time", "max"),
        observations=("time", "size"),
        max_score=("anomaly_score", "max"),
        mean_score=("anomaly_score", "mean")
    )
    .sort_values("observations", ascending=False)
)

print(groups_99.head(20))

                       start_time            end_time  observations  \
anomaly_group
720           2018-02-28 19:00:00 2018-02-28 21:00:00            25
1826          2020-07-19 04:45:00 2020-07-19 06:30:00            22
1342          2018-12-10 18:40:00 2018-12-10 20:20:00            21
874           2018-05-16 20:45:00 2018-05-16 22:25:00            21
250           2017-06-01 08:15:00 2017-06-01 09:45:00            19
252           2017-06-03 16:05:00 2017-06-03 17:30:00            18
1082          2018-07-10 13:35:00 2018-07-10 15:00:00            18
1008          2018-06-19 23:25:00 2018-06-20 00:50:00            18
870           2018-05-16 10:55:00 2018-05-16 12:10:00            16
522           2017-12-12 23:30:00 2017-12-13 00:45:00            16
1802          2020-05-21 11:20:00 2020-05-21 12:35:00            16
702           2018-02-24 09:10:00 2018-02-24 10:25:00            16
536           2017-12-25 07:35:00 2017-12-25 08:50:00            16
1674          2019-10-29 11:25:00 2019-10-29 12:40:00            16
270           2017-06-09 02:15:00 2017-06-09 03:25:00            15
1618          2019-09-03 21:00:00 2019-09-03 22:10:00            15
1642          2019-10-26 12:05:00 2019-10-26 13:15:00            15
534           2017-12-25 06:15:00 2017-12-25 07:25:00            15
476           2017-11-01 19:30:00 2017-11-01 20:40:00            15
1568          2019-07-18 23:25:00 2019-07-19 00:35:00            15

               max_score  mean_score
anomaly_group
720             0.696930    0.648336
1826            0.706428    0.664764
1342            0.714939    0.659558
874             0.722930    0.670374
250             0.692856    0.645131
252             0.719391    0.661224
1082            0.690323    0.631263
1008            0.676919    0.642903
870             0.719836    0.671819
522             0.711089    0.645479
1802            0.698581    0.654240
702             0.705654    0.656666
536             0.674024    0.627329
1674            0.706102    0.643526
270             0.717103    0.677256
1618            0.673680    0.638323
1642            0.681907    0.640676
534             0.700589    0.663059
476             0.712905    0.659747
1568            0.683009    0.646477

In [18]:
threshold_99 = thresholds["99th percentile"]
model_data["anomaly_99"] = (
    model_data["anomaly_score"] >= threshold_99
)
time_gap = model_data["time"].diff()
new_group = (
    model_data["anomaly_99"].ne(model_data["anomaly_99"].shift())
    | time_gap.ne(pd.Timedelta(minutes=5))
)

model_data["anomaly_group"] = new_group.cumsum()

In [19]:
groups_99 = (
    model_data[model_data["anomaly_99"]]
    .groupby("anomaly_group")
    .agg(
        start_time=("time", "min"),
        end_time=("time", "max"),
        observations=("time", "size"),
        max_score=("anomaly_score", "max"),
        mean_score=("anomaly_score", "mean")
    )
    .sort_values(
        ["observations", "mean_score"],
        ascending=False
    )
)

groups_99.head(20)

,start_time,end_time,observations,max_score,mean_score
anomaly_group,,,,,
1027,2018-02-28 19:00:00,2018-02-28 21:00:00,25,0.696930,0.648336
2736,2020-07-19 04:45:00,2020-07-19 06:30:00,22,0.706428,0.664764
1254,2018-05-16 20:45:00,2018-05-16 22:25:00,21,0.722930,0.670374
1886,2018-12-10 18:40:00,2018-12-10 20:20:00,21,0.714939,0.659558
334,2017-06-01 08:15:00,2017-06-01 09:45:00,19,0.692856,0.645131
339,2017-06-03 16:05:00,2017-06-03 17:30:00,18,0.719391,0.661224
1421,2018-06-19 23:25:00,2018-06-20 00:50:00,18,0.676919,0.642903
1495,2018-07-10 13:35:00,2018-07-10 15:00:00,18,0.690323,0.631263
1250,2018-05-16 10:55:00,2018-05-16 12:10:00,16,0.719836,0.671819
1008,2018-02-24 09:10:00,2018-02-24 10:25:00,16,0.705654,0.656666
2652,2020-05-21 11:20:00,2020-05-21 12:35:00,16,0.698581,0.654240
788,2017-12-12 23:30:00,2017-12-13 00:45:00,16,0.711089,0.645479
2421,2019-10-29 11:25:00,2019-10-29 12:40:00,16,0.706102,0.643526
814,2017-12-25 07:35:00,2017-12-25 08:50:00,16,0.674024,0.627329
360,2017-06-09 02:15:00,2017-06-09 03:25:00,15,0.717103,0.677256
528,2017-09-09 04:45:00,2017-09-09 05:55:00,15,0.737177,0.670178
812,2017-12-25 06:15:00,2017-12-25 07:25:00,15,0.700589,0.663059
390,2017-06-14 11:30:00,2017-06-14 12:40:00,15,0.715389,0.661344
730,2017-11-01 19:30:00,2017-11-01 20:40:00,15,0.712905,0.659747
489,2017-08-05 04:20:00,2017-08-05 05:30:00,15,0.688411,0.650730

In [20]:
id="w7q1pz"
start = pd.Timestamp("2017-06-09 02:15:00")
end = pd.Timestamp("2017-06-09 03:25:00")

period = model_data[
    (model_data["time"] >= start) &
    (model_data["time"] <= end)
].copy()
period[sensor_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
Cyclone_Inlet_Gas_Temp,15.0,863.758667,119.383497,613.08,816.670,920.65,935.955,1004.08
Cyclone_Gas_Outlet_Temp,15.0,805.889333,109.927666,604.11,741.675,867.18,882.205,908.67
Cyclone_Outlet_Gas_draft,15.0,-101.567333,23.704631,-134.90,-123.050,-94.19,-88.895,-47.35
Cyclone_cone_draft,15.0,-130.734667,25.996875,-170.75,-149.325,-130.30,-117.400,-79.70
Cyclone_Inlet_Draft,15.0,-78.370667,17.272607,-108.35,-92.175,-74.02,-70.235,-42.61
Cyclone_Material_Temp,15.0,395.772667,394.435183,-96.30,45.220,161.57,800.000,800.00

In [21]:
id="r2v8kx"
period[sensor_cols].agg(["min", "max", "mean", "median"]).T

                             min      max        mean  median
Cyclone_Inlet_Gas_Temp    613.08  1004.08  863.758667  920.65
Cyclone_Gas_Outlet_Temp   604.11   908.67  805.889333  867.18
Cyclone_Outlet_Gas_draft -134.90   -47.35 -101.567333  -94.19
Cyclone_cone_draft       -170.75   -79.70 -130.734667 -130.30
Cyclone_Inlet_Draft      -108.35   -42.61  -78.370667  -74.02
Cyclone_Material_Temp     -96.30   800.00  395.772667  161.57

In [22]:
id="h4m6cs"
period[
    ["time"] +
    sensor_cols +
    ["anomaly_score"]
]

,time,Cyclone_Inlet_Gas_Temp,Cyclone_Gas_Outlet_Temp,Cyclone_Outlet_Gas_draft,Cyclone_cone_draft,Cyclone_Inlet_Draft,Cyclone_Material_Temp,anomaly_score
45819,2017-06-09 02:15:00,613.08,604.11,-47.35,-79.70,-42.61,45.22,0.654321
45820,2017-06-09 02:20:00,651.40,613.60,-87.20,-125.54,-73.16,45.22,0.683681
45821,2017-06-09 02:25:00,707.16,637.45,-88.37,-116.07,-74.02,-96.30,0.685681
45822,2017-06-09 02:30:00,784.18,725.17,-86.44,-98.18,-62.78,45.22,0.716771
45823,2017-06-09 02:35:00,849.16,758.18,-93.63,-118.73,-70.55,45.22,0.714339
45824,2017-06-09 02:40:00,925.46,817.38,-93.27,-99.37,-74.21,45.22,0.717103
45825,2017-06-09 02:45:00,916.69,843.59,-89.42,-135.01,-68.11,45.22,0.713774
45826,2017-06-09 02:50:00,952.13,877.05,-96.22,-129.05,-69.92,161.57,0.705586
45827,2017-06-09 02:55:00,921.85,879.44,-94.19,-130.30,-70.65,800.00,0.678795
45828,2017-06-09 03:00:00,958.77,884.18,-102.32,-136.03,-76.57,800.00,0.665494
45829,2017-06-09 03:05:00,924.08,901.56,-117.51,-146.91,-88.01,800.00,0.660237
45830,2017-06-09 03:10:00,946.45,880.23,-134.90,-170.75,-108.35,800.00,0.673662
45831,2017-06-09 03:15:00,881.24,867.18,-128.59,-153.41,-96.37,800.00,0.626974
45832,2017-06-09 03:20:00,1004.08,890.55,-131.36,-151.74,-96.34,800.00,0.635312
45833,2017-06-09 03:25:00,920.65,908.67,-132.74,-170.23,-103.91,800.00,0.627112

In [23]:
start = pd.Timestamp("2018-02-28 19:00:00")
end = pd.Timestamp("2018-02-28 21:00:00")

period = model_data[
    (model_data["time"] >= start) &
    (model_data["time"] <= end)
].copy()

period[sensor_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
Cyclone_Inlet_Gas_Temp,25.0,904.3404,83.638316,803.10,826.33,889.09,977.14,1076.39
Cyclone_Gas_Outlet_Temp,25.0,871.7780,68.570184,777.84,810.82,847.46,930.94,1014.20
Cyclone_Outlet_Gas_draft,25.0,-135.4968,86.313567,-277.43,-195.56,-128.04,-78.26,19.38
Cyclone_cone_draft,25.0,-150.4492,86.164608,-293.17,-207.14,-142.27,-98.43,8.70
Cyclone_Inlet_Draft,25.0,-113.1052,73.788381,-248.53,-170.52,-98.23,-67.98,18.99
Cyclone_Material_Temp,25.0,976.5228,45.352355,850.77,955.61,980.37,1017.24,1026.87

In [24]:
period[sensor_cols].agg(
    ["min", "max", "mean", "median"]
).T

                             min      max      mean  median
Cyclone_Inlet_Gas_Temp    803.10  1076.39  904.3404  889.09
Cyclone_Gas_Outlet_Temp   777.84  1014.20  871.7780  847.46
Cyclone_Outlet_Gas_draft -277.43    19.38 -135.4968 -128.04
Cyclone_cone_draft       -293.17     8.70 -150.4492 -142.27
Cyclone_Inlet_Draft      -248.53    18.99 -113.1052  -98.23
Cyclone_Material_Temp     850.77  1026.87  976.5228  980.37

In [25]:
period[
    ["time"] + sensor_cols + ["anomaly_score"]
]

,time,Cyclone_Inlet_Gas_Temp,Cyclone_Gas_Outlet_Temp,Cyclone_Outlet_Gas_draft,Cyclone_cone_draft,Cyclone_Inlet_Draft,Cyclone_Material_Temp,anomaly_score
121765,2018-02-28 19:00:00,803.10,777.84,-116.33,-129.50,-93.71,941.96,0.660112
121766,2018-02-28 19:05:00,816.76,805.75,2.00,-10.69,2.11,906.45,0.696930
121767,2018-02-28 19:10:00,818.20,810.13,8.09,-2.65,4.63,931.33,0.668874
121768,2018-02-28 19:15:00,815.78,810.82,19.38,8.70,18.99,964.16,0.659023
121769,2018-02-28 19:20:00,812.79,806.42,-4.82,-19.41,-6.87,980.37,0.680916
121770,2018-02-28 19:25:00,808.65,800.73,-78.26,-104.42,-67.98,978.94,0.688934
121771,2018-02-28 19:30:00,889.09,873.15,-56.97,-83.79,-45.71,987.26,0.648753
121772,2018-02-28 19:35:00,988.81,847.46,-72.43,-86.61,-55.75,1019.59,0.659022
121773,2018-02-28 19:40:00,910.48,844.49,-84.28,-98.43,-72.40,1023.88,0.642363
121774,2018-02-28 19:45:00,977.14,909.32,-104.32,-122.80,-89.84,1023.64,0.644342
121775,2018-02-28 19:50:00,855.70,826.91,-108.36,-117.54,-88.27,1013.39,0.619377
121776,2018-02-28 19:55:00,1076.39,1014.20,-122.72,-137.20,-92.96,1000.38,0.642446
121777,2018-02-28 20:00:00,1047.12,979.26,-128.04,-142.27,-98.23,1022.28,0.608684
121778,2018-02-28 20:05:00,1008.67,964.71,-174.53,-206.07,-145.40,1026.87,0.666377
121779,2018-02-28 20:10:00,881.27,843.31,-195.56,-205.72,-173.55,1017.24,0.648899
121780,2018-02-28 20:15:00,852.81,843.16,-194.20,-206.93,-165.15,978.59,0.612354
121781,2018-02-28 20:20:00,1006.94,970.16,-249.78,-263.41,-219.82,973.83,0.687288
121782,2018-02-28 20:25:00,826.33,790.48,-277.43,-293.17,-248.53,907.14,0.695168
121783,2018-02-28 20:30:00,826.72,815.61,-225.36,-237.52,-188.22,850.77,0.684729
121784,2018-02-28 20:35:00,900.51,900.35,-222.90,-229.35,-181.84,924.93,0.637776
121785,2018-02-28 20:40:00,972.72,936.94,-231.85,-247.63,-184.57,975.76,0.622012
121786,2018-02-28 20:45:00,871.77,850.92,-205.01,-217.97,-170.52,955.61,0.603677
121787,2018-02-28 20:50:00,962.29,930.94,-191.16,-205.39,-158.46,994.03,0.615007
121788,2018-02-28 20:55:00,895.33,883.71,-184.66,-194.32,-151.11,992.31,0.610203
121789,2018-02-28 21:00:00,983.14,957.68,-187.92,-207.14,-154.47,1022.36,0.605129

In [26]:
min_observations = 6   # 6 × 5 minutes = 30 minutes

final_periods = groups_99[
    groups_99["observations"] >= min_observations
].copy()

print("Number of abnormal periods:", len(final_periods))
print()
print(final_periods.head(20))

Number of abnormal periods: 252

                       start_time            end_time  observations  \
anomaly_group
1027          2018-02-28 19:00:00 2018-02-28 21:00:00            25
2736          2020-07-19 04:45:00 2020-07-19 06:30:00            22
1254          2018-05-16 20:45:00 2018-05-16 22:25:00            21
1886          2018-12-10 18:40:00 2018-12-10 20:20:00            21
334           2017-06-01 08:15:00 2017-06-01 09:45:00            19
339           2017-06-03 16:05:00 2017-06-03 17:30:00            18
1421          2018-06-19 23:25:00 2018-06-20 00:50:00            18
1495          2018-07-10 13:35:00 2018-07-10 15:00:00            18
1250          2018-05-16 10:55:00 2018-05-16 12:10:00            16
1008          2018-02-24 09:10:00 2018-02-24 10:25:00            16
2652          2020-05-21 11:20:00 2020-05-21 12:35:00            16
788           2017-12-12 23:30:00 2017-12-13 00:45:00            16
2421          2019-10-29 11:25:00 2019-10-29 12:40:00            16
814           2017-12-25 07:35:00 2017-12-25 08:50:00            16
360           2017-06-09 02:15:00 2017-06-09 03:25:00            15
528           2017-09-09 04:45:00 2017-09-09 05:55:00            15
812           2017-12-25 06:15:00 2017-12-25 07:25:00            15
390           2017-06-14 11:30:00 2017-06-14 12:40:00            15
730           2017-11-01 19:30:00 2017-11-01 20:40:00            15
489           2017-08-05 04:20:00 2017-08-05 05:30:00            15

               max_score  mean_score
anomaly_group
1027            0.696930    0.648336
2736            0.706428    0.664764
1254            0.722930    0.670374
1886            0.714939    0.659558
334             0.692856    0.645131
339             0.719391    0.661224
1421            0.676919    0.642903
1495            0.690323    0.631263
1250            0.719836    0.671819
1008            0.705654    0.656666
2652            0.698581    0.654240
788             0.711089    0.645479
2421            0.706102    0.643526
814             0.674024    0.627329
360             0.717103    0.677256
528             0.737177    0.670178
812             0.700589    0.663059
390             0.715389    0.661344
730             0.712905    0.659747
489             0.688411    0.650730

In [27]:
final_periods = final_periods.reset_index(drop=True)
final_periods["duration"] = (
    final_periods["end_time"] - final_periods["start_time"]
)
final_periods = final_periods[
    [
        "start_time",
        "end_time",
        "duration",
        "observations",
        "max_score",
        "mean_score"
    ]
]

final_periods.head(20)

,start_time,end_time,duration,observations,max_score,mean_score
0,2018-02-28 19:00:00,2018-02-28 21:00:00,0 days 02:00:00,25,0.696930,0.648336
1,2020-07-19 04:45:00,2020-07-19 06:30:00,0 days 01:45:00,22,0.706428,0.664764
2,2018-05-16 20:45:00,2018-05-16 22:25:00,0 days 01:40:00,21,0.722930,0.670374
3,2018-12-10 18:40:00,2018-12-10 20:20:00,0 days 01:40:00,21,0.714939,0.659558
4,2017-06-01 08:15:00,2017-06-01 09:45:00,0 days 01:30:00,19,0.692856,0.645131
5,2017-06-03 16:05:00,2017-06-03 17:30:00,0 days 01:25:00,18,0.719391,0.661224
6,2018-06-19 23:25:00,2018-06-20 00:50:00,0 days 01:25:00,18,0.676919,0.642903
7,2018-07-10 13:35:00,2018-07-10 15:00:00,0 days 01:25:00,18,0.690323,0.631263
8,2018-05-16 10:55:00,2018-05-16 12:10:00,0 days 01:15:00,16,0.719836,0.671819
9,2018-02-24 09:10:00,2018-02-24 10:25:00,0 days 01:15:00,16,0.705654,0.656666
10,2020-05-21 11:20:00,2020-05-21 12:35:00,0 days 01:15:00,16,0.698581,0.654240
11,2017-12-12 23:30:00,2017-12-13 00:45:00,0 days 01:15:00,16,0.711089,0.645479
12,2019-10-29 11:25:00,2019-10-29 12:40:00,0 days 01:15:00,16,0.706102,0.643526
13,2017-12-25 07:35:00,2017-12-25 08:50:00,0 days 01:15:00,16,0.674024,0.627329
14,2017-06-09 02:15:00,2017-06-09 03:25:00,0 days 01:10:00,15,0.717103,0.677256
15,2017-09-09 04:45:00,2017-09-09 05:55:00,0 days 01:10:00,15,0.737177,0.670178
16,2017-12-25 06:15:00,2017-12-25 07:25:00,0 days 01:10:00,15,0.700589,0.663059
17,2017-06-14 11:30:00,2017-06-14 12:40:00,0 days 01:10:00,15,0.715389,0.661344
18,2017-11-01 19:30:00,2017-11-01 20:40:00,0 days 01:10:00,15,0.712905,0.659747
19,2017-08-05 04:20:00,2017-08-05 05:30:00,0 days 01:10:00,15,0.688411,0.650730

In [28]:
final_periods.to_csv(
    "detected_abnormal_periods.csv",
    index=False
)

In [29]:
period = df[
    (df["time"] >= "2018-02-28 19:00:00") &
    (df["time"] <= "2018-02-28 21:00:00")
]

period[
    [
        "time",
        "Cyclone_Inlet_Gas_Temp",
        "Cyclone_Gas_Outlet_Temp",
        "Cyclone_Outlet_Gas_draft",
        "Cyclone_cone_draft",
        "Cyclone_Inlet_Draft",
        "Cyclone_Material_Temp"
    ]
]

,time,Cyclone_Inlet_Gas_Temp,Cyclone_Gas_Outlet_Temp,Cyclone_Outlet_Gas_draft,Cyclone_cone_draft,Cyclone_Inlet_Draft,Cyclone_Material_Temp
121765,2018-02-28 19:00:00,803.10,777.84,-116.33,-129.50,-93.71,941.96
121766,2018-02-28 19:05:00,816.76,805.75,2.00,-10.69,2.11,906.45
121767,2018-02-28 19:10:00,818.20,810.13,8.09,-2.65,4.63,931.33
121768,2018-02-28 19:15:00,815.78,810.82,19.38,8.70,18.99,964.16
121769,2018-02-28 19:20:00,812.79,806.42,-4.82,-19.41,-6.87,980.37
121770,2018-02-28 19:25:00,808.65,800.73,-78.26,-104.42,-67.98,978.94
121771,2018-02-28 19:30:00,889.09,873.15,-56.97,-83.79,-45.71,987.26
121772,2018-02-28 19:35:00,988.81,847.46,-72.43,-86.61,-55.75,1019.59
121773,2018-02-28 19:40:00,910.48,844.49,-84.28,-98.43,-72.40,1023.88
121774,2018-02-28 19:45:00,977.14,909.32,-104.32,-122.80,-89.84,1023.64
121775,2018-02-28 19:50:00,855.70,826.91,-108.36,-117.54,-88.27,1013.39
121776,2018-02-28 19:55:00,1076.39,1014.20,-122.72,-137.20,-92.96,1000.38
121777,2018-02-28 20:00:00,1047.12,979.26,-128.04,-142.27,-98.23,1022.28
121778,2018-02-28 20:05:00,1008.67,964.71,-174.53,-206.07,-145.40,1026.87
121779,2018-02-28 20:10:00,881.27,843.31,-195.56,-205.72,-173.55,1017.24
121780,2018-02-28 20:15:00,852.81,843.16,-194.20,-206.93,-165.15,978.59
121781,2018-02-28 20:20:00,1006.94,970.16,-249.78,-263.41,-219.82,973.83
121782,2018-02-28 20:25:00,826.33,790.48,-277.43,-293.17,-248.53,907.14
121783,2018-02-28 20:30:00,826.72,815.61,-225.36,-237.52,-188.22,850.77
121784,2018-02-28 20:35:00,900.51,900.35,-222.90,-229.35,-181.84,924.93
121785,2018-02-28 20:40:00,972.72,936.94,-231.85,-247.63,-184.57,975.76
121786,2018-02-28 20:45:00,871.77,850.92,-205.01,-217.97,-170.52,955.61
121787,2018-02-28 20:50:00,962.29,930.94,-191.16,-205.39,-158.46,994.03
121788,2018-02-28 20:55:00,895.33,883.71,-184.66,-194.32,-151.11,992.31
121789,2018-02-28 21:00:00,983.14,957.68,-187.92,-207.14,-154.47,1022.36

In [30]:
final_periods[
    [
        "start_time",
        "end_time",
        "duration",
        "observations",
        "max_score",
        "mean_score"
    ]
].to_string(index=False)

'         start_time            end_time        duration  observations  max_score  mean_score\n2018-02-28 19:00:00 2018-02-28 21:00:00 0 days 02:00:00            25   0.696930    0.648336\n2020-07-19 04:45:00 2020-07-19 06:30:00 0 days 01:45:00            22   0.706428    0.664764\n2018-05-16 20:45:00 2018-05-16 22:25:00 0 days 01:40:00            21   0.722930    0.670374\n2018-12-10 18:40:00 2018-12-10 20:20:00 0 days 01:40:00            21   0.714939    0.659558\n2017-06-01 08:15:00 2017-06-01 09:45:00 0 days 01:30:00            19   0.692856    0.645131\n2017-06-03 16:05:00 2017-06-03 17:30:00 0 days 01:25:00            18   0.719391    0.661224\n2018-06-19 23:25:00 2018-06-20 00:50:00 0 days 01:25:00            18   0.676919    0.642903\n2018-07-10 13:35:00 2018-07-10 15:00:00 0 days 01:25:00            18   0.690323    0.631263\n2018-05-16 10:55:00 2018-05-16 12:10:00 0 days 01:15:00            16   0.719836    0.671819\n2018-02-24 09:10:00 2018-02-24 10:25:00 0 days 01:15:00            16   0.705654    0.656666\n2020-05-21 11:20:00 2020-05-21 12:35:00 0 days 01:15:00            16   0.698581    0.654240\n2017-12-12 23:30:00 2017-12-13 00:45:00 0 days 01:15:00            16   0.711089    0.645479\n2019-10-29 11:25:00 2019-10-29 12:40:00 0 days 01:15:00            16   0.706102    0.643526\n2017-12-25 07:35:00 2017-12-25 08:50:00 0 days 01:15:00            16   0.674024    0.627329\n2017-06-09 02:15:00 2017-06-09 03:25:00 0 days 01:10:00            15   0.717103    0.677256\n2017-09-09 04:45:00 2017-09-09 05:55:00 0 days 01:10:00            15   0.737177    0.670178\n2017-12-25 06:15:00 2017-12-25 07:25:00 0 days 01:10:00            15   0.700589    0.663059\n2017-06-14 11:30:00 2017-06-14 12:40:00 0 days 01:10:00            15   0.715389    0.661344\n2017-11-01 19:30:00 2017-11-01 20:40:00 0 days 01:10:00            15   0.712905    0.659747\n2017-08-05 04:20:00 2017-08-05 05:30:00 0 days 01:10:00            15   0.688411    0.650730\n2019-07-18 23:25:00 2019-07-19 00:35:00 0 days 01:10:00            15   0.683009    0.646477\n2019-10-26 12:05:00 2019-10-26 13:15:00 0 days 01:10:00            15   0.681907    0.640676\n2019-09-03 21:00:00 2019-09-03 22:10:00 0 days 01:10:00            15   0.673680    0.638323\n2018-05-23 21:20:00 2018-05-23 22:25:00 0 days 01:05:00            14   0.705097    0.658953\n2017-01-23 01:45:00 2017-01-23 02:50:00 0 days 01:05:00            14   0.692238    0.655777\n2018-08-01 00:00:00 2018-08-01 01:05:00 0 days 01:05:00            14   0.686244    0.654700\n2018-09-15 08:35:00 2018-09-15 09:35:00 0 days 01:00:00            13   0.713336    0.687895\n2017-07-31 04:35:00 2017-07-31 05:35:00 0 days 01:00:00            13   0.714594    0.678543\n2018-11-03 23:40:00 2018-11-04 00:40:00 0 days 01:00:00            13   0.714272    0.673184\n2018-06-28 06:50:00 2018-06-28 07:50:00 0 days 01:00:00            13   0.720677    0.665945\n2020-05-17 10:30:00 2020-05-17 11:30:00 0 days 01:00:00            13   0.708810    0.665938\n2018-04-28 11:45:00 2018-04-28 12:45:00 0 days 01:00:00            13   0.691580    0.647031\n2020-07-17 16:25:00 2020-07-17 17:25:00 0 days 01:00:00            13   0.667319    0.645930\n2018-09-22 09:45:00 2018-09-22 10:45:00 0 days 01:00:00            13   0.681780    0.638892\n2018-02-11 12:15:00 2018-02-11 13:10:00 0 days 00:55:00            12   0.725777    0.694199\n2018-05-31 19:10:00 2018-05-31 20:05:00 0 days 00:55:00            12   0.723424    0.685048\n2018-08-22 18:10:00 2018-08-22 19:05:00 0 days 00:55:00            12   0.714466    0.683196\n2017-12-12 22:00:00 2017-12-12 22:55:00 0 days 00:55:00            12   0.722345    0.681088\n2017-06-08 16:30:00 2017-06-08 17:25:00 0 days 00:55:00            12   0.701223    0.678640\n2018-06-19 17:35:00 2018-06-19 18:30:00 0 days 00:55:00            12   0.710028    0.674855\n2018-10-26 10:40:00 2018-10-26 11:35:00 0 days 00:55:00            12   0.707751    0.672281\n2019-01-12 03:45:00 2019-01-12 04:40:00 0 days 00:55:00            12   0.714322    0.672077\n2019-01-18 11:20:00 2019-01-18 12:15:00 0 days 00:55:00            12   0.701910    0.671737\n2020-05-02 10:55:00 2020-05-02 11:50:00 0 days 00:55:00            12   0.709008    0.669990\n2019-05-05 00:50:00 2019-05-05 01:45:00 0 days 00:55:00            12   0.714413    0.669648\n2018-02-01 13:20:00 2018-02-01 14:15:00 0 days 00:55:00            12   0.707830    0.669421\n2018-04-01 16:00:00 2018-04-01 16:55:00 0 days 00:55:00            12   0.696499    0.668874\n2018-05-02 17:45:00 2018-05-02 18:40:00 0 days 00:55:00            12   0.694364    0.666299\n2017-06-14 01:30:00 2017-06-14 02:25:00 0 days 00:55:00            12   0.689619    0.665680\n2017-03-12 03:35:00 2017-03-12 04:30:00 0 days 00:55:00            12   0.709712    0.665415\n2018-08-29 01:05:00 2018-08-29 02:00:00 0 days 00:55:00            12   0.708950    0.665110\n2018-02-15 20:20:00 2018-02-15 21:15:00 0 days 00:55:00            12   0.685031    0.665061\n2017-05-31 17:45:00 2017-05-31 18:40:00 0 days 00:55:00            12   0.706809    0.664902\n2018-07-13 19:55:00 2018-07-13 20:50:00 0 days 00:55:00            12   0.697276    0.664557\n2019-01-03 05:25:00 2019-01-03 06:20:00 0 days 00:55:00            12   0.684421    0.664406\n2018-03-07 23:05:00 2018-03-08 00:00:00 0 days 00:55:00            12   0.692507    0.664404\n2019-04-29 11:10:00 2019-04-29 12:05:00 0 days 00:55:00            12   0.704584    0.663866\n2018-12-05 22:45:00 2018-12-05 23:40:00 0 days 00:55:00            12   0.686426    0.660801\n2017-09-12 21:20:00 2017-09-12 22:15:00 0 days 00:55:00            12   0.706189    0.660776\n2020-05-28 01:35:00 2020-05-28 02:30:00 0 days 00:55:00            12   0.695747    0.659391\n2019-11-29 11:40:00 2019-11-29 12:35:00 0 days 00:55:00            12   0.692866    0.659367\n2018-07-04 20:00:00 2018-07-04 20:55:00 0 days 00:55:00            12   0.681648    0.659061\n2020-07-17 14:40:00 2020-07-17 15:35:00 0 days 00:55:00            12   0.703419    0.658195\n2018-06-27 14:05:00 2018-06-27 15:00:00 0 days 00:55:00            12   0.693740    0.656937\n2017-06-04 16:00:00 2017-06-04 16:55:00 0 days 00:55:00            12   0.711001    0.656285\n2017-12-27 17:35:00 2017-12-27 18:30:00 0 days 00:55:00            12   0.703007    0.655292\n2018-04-29 01:50:00 2018-04-29 02:45:00 0 days 00:55:00            12   0.688130    0.654189\n2020-01-29 03:05:00 2020-01-29 04:00:00 0 days 00:55:00            12   0.690812    0.652392\n2020-02-23 09:10:00 2020-02-23 10:05:00 0 days 00:55:00            12   0.702345    0.650288\n2020-05-17 21:00:00 2020-05-17 21:55:00 0 days 00:55:00            12   0.677152    0.647703\n2018-12-09 13:25:00 2018-12-09 14:20:00 0 days 00:55:00            12   0.683629    0.645636\n2017-03-21 03:05:00 2017-03-21 04:00:00 0 days 00:55:00            12   0.674172    0.639649\n2017-01-22 23:25:00 2017-01-23 00:20:00 0 days 00:55:00            12   0.667544    0.638403\n2018-12-13 15:05:00 2018-12-13 16:00:00 0 days 00:55:00            12   0.665054    0.637503\n2017-03-30 23:40:00 2017-03-31 00:35:00 0 days 00:55:00            12   0.676417    0.636337\n2017-09-14 03:00:00 2017-09-14 03:55:00 0 days 00:55:00            12   0.665316    0.635539\n2018-07-13 22:30:00 2018-07-13 23:25:00 0 days 00:55:00            12   0.672399    0.634746\n2017-06-16 19:25:00 2017-06-16 20:20:00 0 days 00:55:00            12   0.650953    0.630806\n2020-03-02 17:25:00 2020-03-02 18:20:00 0 days 00:55:00            12   0.643705    0.622482\n2018-11-27 05:40:00 2018-11-27 06:30:00 0 days 00:50:00            11   0.740618    0.703044\n2018-07-15 01:45:00 2018-07-15 02:35:00 0 days 00:50:00            11   0.714736    0.681778\n2019-02-25 14:50:00 2019-02-25 15:40:00 0 days 00:50:00            11   0.714483    0.680432\n2019-04-21 07:15:00 2019-04-21 08:05:00 0 days 00:50:00            11   0.713588    0.676336\n2019-11-08 16:30:00 2019-11-08 17:20:00 0 days 00:50:00            11   0.698821    0.675694\n2019-02-01 10:30:00 2019-02-01 11:20:00 0 days 00:50:00            11   0.714515    0.675055\n2017-09-14 01:10:00 2017-09-14 02:00:00 0 days 00:50:00            11   0.714251    0.675004\n2018-05-21 23:40:00 2018-05-22 00:30:00 0 days 00:50:00            11   0.709522    0.673664\n2018-01-16 15:15:00 2018-01-16 16:05:00 0 days 00:50:00            11   0.694985    0.669583\n2017-10-31 21:20:00 2017-10-31 22:10:00 0 days 00:50:00            11   0.706928    0.669215\n2018-05-19 13:05:00 2018-05-19 13:55:00 0 days 00:50:00            11   0.713625    0.668971\n2019-04-07 15:30:00 2019-04-07 16:20:00 0 days 00:50:00            11   0.713291    0.668098\n2017-04-05 01:30:00 2017-04-05 02:20:00 0 days 00:50:00            11   0.697734    0.667042\n2018-06-18 05:00:00 2018-06-18 05:50:00 0 days 00:50:00            11   0.706179    0.666562\n2020-07-30 10:00:00 2020-07-30 10:50:00 0 days 00:50:00            11   0.694960    0.666291\n2019-11-20 16:10:00 2019-11-20 17:00:00 0 days 00:50:00            11   0.688081    0.666222\n2019-09-14 07:25:00 2019-09-14 08:15:00 0 days 00:50:00            11   0.703159    0.666175\n2019-08-01 15:55:00 2019-08-01 16:45:00 0 days 00:50:00            11   0.688316    0.664518\n2018-06-19 22:20:00 2018-06-19 23:10:00 0 days 00:50:00            11   0.678637    0.663054\n2019-02-11 16:10:00 2019-02-11 17:00:00 0 days 00:50:00            11   0.687336    0.662815\n2019-06-30 22:20:00 2019-06-30 23:10:00 0 days 00:50:00            11   0.688119    0.662377\n2019-08-17 08:40:00 2019-08-17 09:30:00 0 days 00:50:00            11   0.710668    0.661510\n2017-01-25 16:20:00 2017-01-25 17:10:00 0 days 00:50:00            11   0.683331    0.661103\n2018-12-22 10:20:00 2018-12-22 11:10:00 0 days 00:50:00            11   0.693371    0.659886\n2018-02-26 07:15:00 2018-02-26 08:05:00 0 days 00:50:00            11   0.708913    0.659189\n2017-10-27 10:00:00 2017-10-27 10:50:00 0 days 00:50:00            11   0.695136    0.656976\n2017-05-31 20:35:00 2017-05-31 21:25:00 0 days 00:50:00            11   0.680663    0.656117\n2018-05-16 17:05:00 2018-05-16 17:55:00 0 days 00:50:00            11   0.666484    0.655205\n2018-03-07 19:25:00 2018-03-07 20:15:00 0 days 00:50:00            11   0.694846    0.654306\n2017-12-28 11:10:00 2017-12-28 12:00:00 0 days 00:50:00            11   0.709473    0.653545\n2017-06-12 12:35:00 2017-06-12 13:25:00 0 days 00:50:00            11   0.673926    0.653168\n2019-04-14 18:50:00 2019-04-14 19:40:00 0 days 00:50:00            11   0.689747    0.652798\n2017-05-19 00:55:00 2017-05-19 01:45:00 0 days 00:50:00            11   0.701973    0.652611\n2018-07-29 21:55:00 2018-07-29 22:45:00 0 days 00:50:00            11   0.708577    0.652217\n2019-02-01 03:05:00 2019-02-01 03:55:00 0 days 00:50:00            11   0.707816    0.651811\n2017-03-02 03:45:00 2017-03-02 04:35:00 0 days 00:50:00            11   0.677772    0.651724\n2017-08-05 03:20:00 2017-08-05 04:10:00 0 days 00:50:00            11   0.688517    0.651504\n2017-11-27 20:30:00 2017-11-27 21:20:00 0 days 00:50:00            11   0.665913    0.650799\n2018-03-13 02:25:00 2018-03-13 03:15:00 0 days 00:50:00            11   0.683249    0.648808\n2017-01-23 13:05:00 2017-01-23 13:55:00 0 days 00:50:00            11   0.674034    0.647057\n2019-07-16 08:05:00 2019-07-16 08:55:00 0 days 00:50:00            11   0.678340    0.646243\n2017-10-20 02:50:00 2017-10-20 03:40:00 0 days 00:50:00            11   0.678712    0.644709\n2017-09-13 23:10:00 2017-09-14 00:00:00 0 days 00:50:00            11   0.674502    0.644345\n2018-09-02 22:30:00 2018-09-02 23:20:00 0 days 00:50:00            11   0.692318    0.643134\n2017-06-16 21:45:00 2017-06-16 22:35:00 0 days 00:50:00            11   0.689740    0.642488\n2020-02-22 05:10:00 2020-02-22 06:00:00 0 days 00:50:00            11   0.663918    0.642088\n2019-07-19 13:40:00 2019-07-19 14:30:00 0 days 00:50:00            11   0.671397    0.641967\n2018-10-23 10:15:00 2018-10-23 11:05:00 0 days 00:50:00            11   0.671935    0.640309\n2017-09-19 00:35:00 2017-09-19 01:25:00 0 days 00:50:00            11   0.674828    0.639966\n2017-09-17 19:15:00 2017-09-17 20:05:00 0 days 00:50:00            11   0.669860    0.638984\n2018-07-30 00:10:00 2018-07-30 01:00:00 0 days 00:50:00            11   0.670446    0.637208\n2017-10-31 23:40:00 2017-11-01 00:30:00 0 days 00:50:00            11   0.681632    0.637033\n2019-02-04 17:25:00 2019-02-04 18:15:00 0 days 00:50:00            11   0.677707    0.635443\n2018-06-01 02:15:00 2018-06-01 03:05:00 0 days 00:50:00            11   0.654049    0.634391\n2018-04-04 03:30:00 2018-04-04 04:20:00 0 days 00:50:00            11   0.672540    0.631323\n2019-05-14 04:40:00 2019-05-14 05:30:00 0 days 00:50:00            11   0.655558    0.631178\n2020-07-26 06:40:00 2020-07-26 07:25:00 0 days 00:45:00            10   0.714308    0.678519\n2017-11-04 09:15:00 2017-11-04 10:00:00 0 days 00:45:00            10   0.681087    0.664001\n2018-05-08 02:35:00 2018-05-08 03:20:00 0 days 00:45:00            10   0.706280    0.657589\n2017-03-29 21:40:00 2017-03-29 22:25:00 0 days 00:45:00            10   0.692829    0.656497\n2018-07-19 06:50:00 2018-07-19 07:35:00 0 days 00:45:00            10   0.695138    0.652701\n2018-06-10 03:40:00 2018-06-10 04:25:00 0 days 00:45:00            10   0.674620    0.652472\n2017-07-20 09:10:00 2017-07-20 09:55:00 0 days 00:45:00            10   0.680352    0.650961\n2018-01-16 18:55:00 2018-01-16 19:40:00 0 days 00:45:00            10   0.697514    0.650581\n2019-08-31 04:40:00 2019-08-31 05:25:00 0 days 00:45:00            10   0.705638    0.646117\n2018-05-04 14:20:00 2018-05-04 15:05:00 0 days 00:45:00            10   0.686574    0.645127\n2017-01-23 14:55:00 2017-01-23 15:40:00 0 days 00:45:00            10   0.670656    0.642468\n2019-11-08 20:15:00 2019-11-08 21:00:00 0 days 00:45:00            10   0.692860    0.641511\n2018-03-20 00:15:00 2018-03-20 01:00:00 0 days 00:45:00            10   0.675096    0.640299\n2018-05-01 14:55:00 2018-05-01 15:40:00 0 days 00:45:00            10   0.665278    0.638260\n2017-03-02 07:35:00 2017-03-02 08:20:00 0 days 00:45:00            10   0.655521    0.636280\n2020-07-26 12:10:00 2020-07-26 12:55:00 0 days 00:45:00            10   0.664933    0.630682\n2019-03-09 05:55:00 2019-03-09 06:40:00 0 days 00:45:00            10   0.675374    0.623476\n2018-05-09 12:05:00 2018-05-09 12:45:00 0 days 00:40:00             9   0.723763    0.691307\n2018-08-06 16:45:00 2018-08-06 17:25:00 0 days 00:40:00             9   0.707103    0.664035\n2018-05-10 11:15:00 2018-05-10 11:55:00 0 days 00:40:00             9   0.685283    0.659305\n2019-04-04 14:50:00 2019-04-04 15:30:00 0 days 00:40:00             9   0.709314    0.656272\n2018-11-13 17:15:00 2018-11-13 17:55:00 0 days 00:40:00             9   0.685402    0.651997\n2017-03-25 03:30:00 2017-03-25 04:10:00 0 days 00:40:00             9   0.683281    0.651897\n2020-02-23 10:40:00 2020-02-23 11:20:00 0 days 00:40:00             9   0.675180    0.651837\n2019-04-30 12:15:00 2019-04-30 12:55:00 0 days 00:40:00             9   0.664524    0.649433\n2018-10-25 17:00:00 2018-10-25 17:40:00 0 days 00:40:00             9   0.688284    0.646595\n2017-06-22 06:10:00 2017-06-22 06:50:00 0 days 00:40:00             9   0.674822    0.643114\n2020-03-22 19:50:00 2020-03-22 20:30:00 0 days 00:40:00             9   0.675093    0.642607\n2017-04-03 15:00:00 2017-04-03 15:40:00 0 days 00:40:00             9   0.688008    0.642073\n2017-04-07 01:00:00 2017-04-07 01:40:00 0 days 00:40:00             9   0.674000    0.641474\n2018-11-05 11:10:00 2018-11-05 11:50:00 0 days 00:40:00             9   0.662625    0.639403\n2017-12-27 20:20:00 2017-12-27 21:00:00 0 days 00:40:00             9   0.682968    0.638719\n2018-06-05 11:50:00 2018-06-05 12:30:00 0 days 00:40:00             9   0.655396    0.634081\n2017-01-25 17:45:00 2017-01-25 18:25:00 0 days 00:40:00             9   0.661168    0.633905\n2017-04-29 00:30:00 2017-04-29 01:10:00 0 days 00:40:00             9   0.665420    0.632261\n2019-10-26 15:10:00 2019-10-26 15:50:00 0 days 00:40:00             9   0.652050    0.629428\n2018-03-08 01:15:00 2018-03-08 01:55:00 0 days 00:40:00             9   0.656051    0.625851\n2019-07-01 03:05:00 2019-07-01 03:45:00 0 days 00:40:00             9   0.648977    0.625708\n2018-06-28 11:15:00 2018-06-28 11:55:00 0 days 00:40:00             9   0.652528    0.625450\n2018-05-09 13:50:00 2018-05-09 14:30:00 0 days 00:40:00             9   0.636631    0.619644\n2018-09-25 15:30:00 2018-09-25 16:10:00 0 days 00:40:00             9   0.644080    0.617072\n2018-08-21 12:10:00 2018-08-21 12:45:00 0 days 00:35:00             8   0.702679    0.666357\n2019-03-18 15:50:00 2019-03-18 16:25:00 0 days 00:35:00             8   0.713247    0.649268\n2017-05-31 22:30:00 2017-05-31 23:05:00 0 days 00:35:00             8   0.681397    0.647499\n2018-02-06 08:00:00 2018-02-06 08:35:00 0 days 00:35:00             8   0.686792    0.645931\n2017-09-09 12:55:00 2017-09-09 13:30:00 0 days 00:35:00             8   0.683778    0.641615\n2018-06-27 16:20:00 2018-06-27 16:55:00 0 days 00:35:00             8   0.656266    0.640953\n2017-06-06 14:20:00 2017-06-06 14:55:00 0 days 00:35:00             8   0.668551    0.638922\n2018-02-17 22:20:00 2018-02-17 22:55:00 0 days 00:35:00             8   0.694356    0.635840\n2019-08-17 12:55:00 2019-08-17 13:30:00 0 days 00:35:00             8   0.669244    0.635641\n2017-03-30 22:05:00 2017-03-30 22:40:00 0 days 00:35:00             8   0.671563    0.635632\n2019-05-14 09:10:00 2019-05-14 09:45:00 0 days 00:35:00             8   0.649492    0.632752\n2017-11-16 19:30:00 2017-11-16 20:05:00 0 days 00:35:00             8   0.662482    0.632085\n2017-06-12 13:35:00 2017-06-12 14:10:00 0 days 00:35:00             8   0.654503    0.630619\n2018-06-19 14:55:00 2018-06-19 15:30:00 0 days 00:35:00             8   0.653286    0.628466\n2019-11-20 17:25:00 2019-11-20 18:00:00 0 days 00:35:00             8   0.656347    0.627532\n2018-08-12 15:30:00 2018-08-12 16:05:00 0 days 00:35:00             8   0.636867    0.620269\n2018-03-19 05:00:00 2018-03-19 05:35:00 0 days 00:35:00             8   0.622616    0.615184\n2017-07-28 01:10:00 2017-07-28 01:40:00 0 days 00:30:00             7   0.702581    0.663094\n2018-11-13 14:35:00 2018-11-13 15:05:00 0 days 00:30:00             7   0.687874    0.654836\n2017-04-04 17:15:00 2017-04-04 17:45:00 0 days 00:30:00             7   0.707495    0.654655\n2017-06-16 22:50:00 2017-06-16 23:20:00 0 days 00:30:00             7   0.700174    0.652193\n2018-03-21 03:45:00 2018-03-21 04:15:00 0 days 00:30:00             7   0.678381    0.646201\n2017-10-20 04:40:00 2017-10-20 05:10:00 0 days 00:30:00             7   0.675322    0.644877\n2017-09-19 02:30:00 2017-09-19 03:00:00 0 days 00:30:00             7   0.690892    0.641646\n2018-02-22 13:10:00 2018-02-22 13:40:00 0 days 00:30:00             7   0.669212    0.641588\n2019-10-27 16:55:00 2019-10-27 17:25:00 0 days 00:30:00             7   0.677016    0.638898\n2017-06-24 20:25:00 2017-06-24 20:55:00 0 days 00:30:00             7   0.677335    0.637976\n2018-06-27 15:20:00 2018-06-27 15:50:00 0 days 00:30:00             7   0.656699    0.637115\n2018-07-19 07:50:00 2018-07-19 08:20:00 0 days 00:30:00             7   0.663845    0.636267\n2019-05-14 03:20:00 2019-05-14 03:50:00 0 days 00:30:00             7   0.661148    0.634750\n2018-05-23 22:50:00 2018-05-23 23:20:00 0 days 00:30:00             7   0.665089    0.634588\n2018-04-14 09:20:00 2018-04-14 09:50:00 0 days 00:30:00             7   0.658545    0.634083\n2018-07-14 10:15:00 2018-07-14 10:45:00 0 days 00:30:00             7   0.659948    0.633304\n2017-10-27 18:20:00 2017-10-27 18:50:00 0 days 00:30:00             7   0.657355    0.632478\n2020-05-26 11:10:00 2020-05-26 11:40:00 0 days 00:30:00             7   0.654333    0.632449\n2018-09-17 16:55:00 2018-09-17 17:25:00 0 days 00:30:00             7  

In [31]:
final_periods["year"] = final_periods["start_time"].dt.year

final_periods["year"].value_counts().sort_index()

year
2017     80
2018    102
2019     49
2020     21
Name: count, dtype: int64

In [32]:
final_periods.groupby("year")["duration"].sum()

year
2017   2 days 14:30:00
2018   3 days 07:10:00
2019   1 days 12:35:00
2020   0 days 17:40:00
Name: duration, dtype: timedelta64[us]

In [33]:
final_periods[
    [
        "start_time",
        "end_time",
        "duration",
        "observations",
        "max_score",
        "mean_score"
    ]
].to_string(index=False)

'         start_time            end_time        duration  observations  max_score  mean_score\n2018-02-28 19:00:00 2018-02-28 21:00:00 0 days 02:00:00            25   0.696930    0.648336\n2020-07-19 04:45:00 2020-07-19 06:30:00 0 days 01:45:00            22   0.706428    0.664764\n2018-05-16 20:45:00 2018-05-16 22:25:00 0 days 01:40:00            21   0.722930    0.670374\n2018-12-10 18:40:00 2018-12-10 20:20:00 0 days 01:40:00            21   0.714939    0.659558\n2017-06-01 08:15:00 2017-06-01 09:45:00 0 days 01:30:00            19   0.692856    0.645131\n2017-06-03 16:05:00 2017-06-03 17:30:00 0 days 01:25:00            18   0.719391    0.661224\n2018-06-19 23:25:00 2018-06-20 00:50:00 0 days 01:25:00            18   0.676919    0.642903\n2018-07-10 13:35:00 2018-07-10 15:00:00 0 days 01:25:00            18   0.690323    0.631263\n2018-05-16 10:55:00 2018-05-16 12:10:00 0 days 01:15:00            16   0.719836    0.671819\n2018-02-24 09:10:00 2018-02-24 10:25:00 0 days 01:15:00            16   0.705654    0.656666\n2020-05-21 11:20:00 2020-05-21 12:35:00 0 days 01:15:00            16   0.698581    0.654240\n2017-12-12 23:30:00 2017-12-13 00:45:00 0 days 01:15:00            16   0.711089    0.645479\n2019-10-29 11:25:00 2019-10-29 12:40:00 0 days 01:15:00            16   0.706102    0.643526\n2017-12-25 07:35:00 2017-12-25 08:50:00 0 days 01:15:00            16   0.674024    0.627329\n2017-06-09 02:15:00 2017-06-09 03:25:00 0 days 01:10:00            15   0.717103    0.677256\n2017-09-09 04:45:00 2017-09-09 05:55:00 0 days 01:10:00            15   0.737177    0.670178\n2017-12-25 06:15:00 2017-12-25 07:25:00 0 days 01:10:00            15   0.700589    0.663059\n2017-06-14 11:30:00 2017-06-14 12:40:00 0 days 01:10:00            15   0.715389    0.661344\n2017-11-01 19:30:00 2017-11-01 20:40:00 0 days 01:10:00            15   0.712905    0.659747\n2017-08-05 04:20:00 2017-08-05 05:30:00 0 days 01:10:00            15   0.688411    0.650730\n2019-07-18 23:25:00 2019-07-19 00:35:00 0 days 01:10:00            15   0.683009    0.646477\n2019-10-26 12:05:00 2019-10-26 13:15:00 0 days 01:10:00            15   0.681907    0.640676\n2019-09-03 21:00:00 2019-09-03 22:10:00 0 days 01:10:00            15   0.673680    0.638323\n2018-05-23 21:20:00 2018-05-23 22:25:00 0 days 01:05:00            14   0.705097    0.658953\n2017-01-23 01:45:00 2017-01-23 02:50:00 0 days 01:05:00            14   0.692238    0.655777\n2018-08-01 00:00:00 2018-08-01 01:05:00 0 days 01:05:00            14   0.686244    0.654700\n2018-09-15 08:35:00 2018-09-15 09:35:00 0 days 01:00:00            13   0.713336    0.687895\n2017-07-31 04:35:00 2017-07-31 05:35:00 0 days 01:00:00            13   0.714594    0.678543\n2018-11-03 23:40:00 2018-11-04 00:40:00 0 days 01:00:00            13   0.714272    0.673184\n2018-06-28 06:50:00 2018-06-28 07:50:00 0 days 01:00:00            13   0.720677    0.665945\n2020-05-17 10:30:00 2020-05-17 11:30:00 0 days 01:00:00            13   0.708810    0.665938\n2018-04-28 11:45:00 2018-04-28 12:45:00 0 days 01:00:00            13   0.691580    0.647031\n2020-07-17 16:25:00 2020-07-17 17:25:00 0 days 01:00:00            13   0.667319    0.645930\n2018-09-22 09:45:00 2018-09-22 10:45:00 0 days 01:00:00            13   0.681780    0.638892\n2018-02-11 12:15:00 2018-02-11 13:10:00 0 days 00:55:00            12   0.725777    0.694199\n2018-05-31 19:10:00 2018-05-31 20:05:00 0 days 00:55:00            12   0.723424    0.685048\n2018-08-22 18:10:00 2018-08-22 19:05:00 0 days 00:55:00            12   0.714466    0.683196\n2017-12-12 22:00:00 2017-12-12 22:55:00 0 days 00:55:00            12   0.722345    0.681088\n2017-06-08 16:30:00 2017-06-08 17:25:00 0 days 00:55:00            12   0.701223    0.678640\n2018-06-19 17:35:00 2018-06-19 18:30:00 0 days 00:55:00            12   0.710028    0.674855\n2018-10-26 10:40:00 2018-10-26 11:35:00 0 days 00:55:00            12   0.707751    0.672281\n2019-01-12 03:45:00 2019-01-12 04:40:00 0 days 00:55:00            12   0.714322    0.672077\n2019-01-18 11:20:00 2019-01-18 12:15:00 0 days 00:55:00            12   0.701910    0.671737\n2020-05-02 10:55:00 2020-05-02 11:50:00 0 days 00:55:00            12   0.709008    0.669990\n2019-05-05 00:50:00 2019-05-05 01:45:00 0 days 00:55:00            12   0.714413    0.669648\n2018-02-01 13:20:00 2018-02-01 14:15:00 0 days 00:55:00            12   0.707830    0.669421\n2018-04-01 16:00:00 2018-04-01 16:55:00 0 days 00:55:00            12   0.696499    0.668874\n2018-05-02 17:45:00 2018-05-02 18:40:00 0 days 00:55:00            12   0.694364    0.666299\n2017-06-14 01:30:00 2017-06-14 02:25:00 0 days 00:55:00            12   0.689619    0.665680\n2017-03-12 03:35:00 2017-03-12 04:30:00 0 days 00:55:00            12   0.709712    0.665415\n2018-08-29 01:05:00 2018-08-29 02:00:00 0 days 00:55:00            12   0.708950    0.665110\n2018-02-15 20:20:00 2018-02-15 21:15:00 0 days 00:55:00            12   0.685031    0.665061\n2017-05-31 17:45:00 2017-05-31 18:40:00 0 days 00:55:00            12   0.706809    0.664902\n2018-07-13 19:55:00 2018-07-13 20:50:00 0 days 00:55:00            12   0.697276    0.664557\n2019-01-03 05:25:00 2019-01-03 06:20:00 0 days 00:55:00            12   0.684421    0.664406\n2018-03-07 23:05:00 2018-03-08 00:00:00 0 days 00:55:00            12   0.692507    0.664404\n2019-04-29 11:10:00 2019-04-29 12:05:00 0 days 00:55:00            12   0.704584    0.663866\n2018-12-05 22:45:00 2018-12-05 23:40:00 0 days 00:55:00            12   0.686426    0.660801\n2017-09-12 21:20:00 2017-09-12 22:15:00 0 days 00:55:00            12   0.706189    0.660776\n2020-05-28 01:35:00 2020-05-28 02:30:00 0 days 00:55:00            12   0.695747    0.659391\n2019-11-29 11:40:00 2019-11-29 12:35:00 0 days 00:55:00            12   0.692866    0.659367\n2018-07-04 20:00:00 2018-07-04 20:55:00 0 days 00:55:00            12   0.681648    0.659061\n2020-07-17 14:40:00 2020-07-17 15:35:00 0 days 00:55:00            12   0.703419    0.658195\n2018-06-27 14:05:00 2018-06-27 15:00:00 0 days 00:55:00            12   0.693740    0.656937\n2017-06-04 16:00:00 2017-06-04 16:55:00 0 days 00:55:00            12   0.711001    0.656285\n2017-12-27 17:35:00 2017-12-27 18:30:00 0 days 00:55:00            12   0.703007    0.655292\n2018-04-29 01:50:00 2018-04-29 02:45:00 0 days 00:55:00            12   0.688130    0.654189\n2020-01-29 03:05:00 2020-01-29 04:00:00 0 days 00:55:00            12   0.690812    0.652392\n2020-02-23 09:10:00 2020-02-23 10:05:00 0 days 00:55:00            12   0.702345    0.650288\n2020-05-17 21:00:00 2020-05-17 21:55:00 0 days 00:55:00            12   0.677152    0.647703\n2018-12-09 13:25:00 2018-12-09 14:20:00 0 days 00:55:00            12   0.683629    0.645636\n2017-03-21 03:05:00 2017-03-21 04:00:00 0 days 00:55:00            12   0.674172    0.639649\n2017-01-22 23:25:00 2017-01-23 00:20:00 0 days 00:55:00            12   0.667544    0.638403\n2018-12-13 15:05:00 2018-12-13 16:00:00 0 days 00:55:00            12   0.665054    0.637503\n2017-03-30 23:40:00 2017-03-31 00:35:00 0 days 00:55:00            12   0.676417    0.636337\n2017-09-14 03:00:00 2017-09-14 03:55:00 0 days 00:55:00            12   0.665316    0.635539\n2018-07-13 22:30:00 2018-07-13 23:25:00 0 days 00:55:00            12   0.672399    0.634746\n2017-06-16 19:25:00 2017-06-16 20:20:00 0 days 00:55:00            12   0.650953    0.630806\n2020-03-02 17:25:00 2020-03-02 18:20:00 0 days 00:55:00            12   0.643705    0.622482\n2018-11-27 05:40:00 2018-11-27 06:30:00 0 days 00:50:00            11   0.740618    0.703044\n2018-07-15 01:45:00 2018-07-15 02:35:00 0 days 00:50:00            11   0.714736    0.681778\n2019-02-25 14:50:00 2019-02-25 15:40:00 0 days 00:50:00            11   0.714483    0.680432\n2019-04-21 07:15:00 2019-04-21 08:05:00 0 days 00:50:00            11   0.713588    0.676336\n2019-11-08 16:30:00 2019-11-08 17:20:00 0 days 00:50:00            11   0.698821    0.675694\n2019-02-01 10:30:00 2019-02-01 11:20:00 0 days 00:50:00            11   0.714515    0.675055\n2017-09-14 01:10:00 2017-09-14 02:00:00 0 days 00:50:00            11   0.714251    0.675004\n2018-05-21 23:40:00 2018-05-22 00:30:00 0 days 00:50:00            11   0.709522    0.673664\n2018-01-16 15:15:00 2018-01-16 16:05:00 0 days 00:50:00            11   0.694985    0.669583\n2017-10-31 21:20:00 2017-10-31 22:10:00 0 days 00:50:00            11   0.706928    0.669215\n2018-05-19 13:05:00 2018-05-19 13:55:00 0 days 00:50:00            11   0.713625    0.668971\n2019-04-07 15:30:00 2019-04-07 16:20:00 0 days 00:50:00            11   0.713291    0.668098\n2017-04-05 01:30:00 2017-04-05 02:20:00 0 days 00:50:00            11   0.697734    0.667042\n2018-06-18 05:00:00 2018-06-18 05:50:00 0 days 00:50:00            11   0.706179    0.666562\n2020-07-30 10:00:00 2020-07-30 10:50:00 0 days 00:50:00            11   0.694960    0.666291\n2019-11-20 16:10:00 2019-11-20 17:00:00 0 days 00:50:00            11   0.688081    0.666222\n2019-09-14 07:25:00 2019-09-14 08:15:00 0 days 00:50:00            11   0.703159    0.666175\n2019-08-01 15:55:00 2019-08-01 16:45:00 0 days 00:50:00            11   0.688316    0.664518\n2018-06-19 22:20:00 2018-06-19 23:10:00 0 days 00:50:00            11   0.678637    0.663054\n2019-02-11 16:10:00 2019-02-11 17:00:00 0 days 00:50:00            11   0.687336    0.662815\n2019-06-30 22:20:00 2019-06-30 23:10:00 0 days 00:50:00            11   0.688119    0.662377\n2019-08-17 08:40:00 2019-08-17 09:30:00 0 days 00:50:00            11   0.710668    0.661510\n2017-01-25 16:20:00 2017-01-25 17:10:00 0 days 00:50:00            11   0.683331    0.661103\n2018-12-22 10:20:00 2018-12-22 11:10:00 0 days 00:50:00            11   0.693371    0.659886\n2018-02-26 07:15:00 2018-02-26 08:05:00 0 days 00:50:00            11   0.708913    0.659189\n2017-10-27 10:00:00 2017-10-27 10:50:00 0 days 00:50:00            11   0.695136    0.656976\n2017-05-31 20:35:00 2017-05-31 21:25:00 0 days 00:50:00            11   0.680663    0.656117\n2018-05-16 17:05:00 2018-05-16 17:55:00 0 days 00:50:00            11   0.666484    0.655205\n2018-03-07 19:25:00 2018-03-07 20:15:00 0 days 00:50:00            11   0.694846    0.654306\n2017-12-28 11:10:00 2017-12-28 12:00:00 0 days 00:50:00            11   0.709473    0.653545\n2017-06-12 12:35:00 2017-06-12 13:25:00 0 days 00:50:00            11   0.673926    0.653168\n2019-04-14 18:50:00 2019-04-14 19:40:00 0 days 00:50:00            11   0.689747    0.652798\n2017-05-19 00:55:00 2017-05-19 01:45:00 0 days 00:50:00            11   0.701973    0.652611\n2018-07-29 21:55:00 2018-07-29 22:45:00 0 days 00:50:00            11   0.708577    0.652217\n2019-02-01 03:05:00 2019-02-01 03:55:00 0 days 00:50:00            11   0.707816    0.651811\n2017-03-02 03:45:00 2017-03-02 04:35:00 0 days 00:50:00            11   0.677772    0.651724\n2017-08-05 03:20:00 2017-08-05 04:10:00 0 days 00:50:00            11   0.688517    0.651504\n2017-11-27 20:30:00 2017-11-27 21:20:00 0 days 00:50:00            11   0.665913    0.650799\n2018-03-13 02:25:00 2018-03-13 03:15:00 0 days 00:50:00            11   0.683249    0.648808\n2017-01-23 13:05:00 2017-01-23 13:55:00 0 days 00:50:00            11   0.674034    0.647057\n2019-07-16 08:05:00 2019-07-16 08:55:00 0 days 00:50:00            11   0.678340    0.646243\n2017-10-20 02:50:00 2017-10-20 03:40:00 0 days 00:50:00            11   0.678712    0.644709\n2017-09-13 23:10:00 2017-09-14 00:00:00 0 days 00:50:00            11   0.674502    0.644345\n2018-09-02 22:30:00 2018-09-02 23:20:00 0 days 00:50:00            11   0.692318    0.643134\n2017-06-16 21:45:00 2017-06-16 22:35:00 0 days 00:50:00            11   0.689740    0.642488\n2020-02-22 05:10:00 2020-02-22 06:00:00 0 days 00:50:00            11   0.663918    0.642088\n2019-07-19 13:40:00 2019-07-19 14:30:00 0 days 00:50:00            11   0.671397    0.641967\n2018-10-23 10:15:00 2018-10-23 11:05:00 0 days 00:50:00            11   0.671935    0.640309\n2017-09-19 00:35:00 2017-09-19 01:25:00 0 days 00:50:00            11   0.674828    0.639966\n2017-09-17 19:15:00 2017-09-17 20:05:00 0 days 00:50:00            11   0.669860    0.638984\n2018-07-30 00:10:00 2018-07-30 01:00:00 0 days 00:50:00            11   0.670446    0.637208\n2017-10-31 23:40:00 2017-11-01 00:30:00 0 days 00:50:00            11   0.681632    0.637033\n2019-02-04 17:25:00 2019-02-04 18:15:00 0 days 00:50:00            11   0.677707    0.635443\n2018-06-01 02:15:00 2018-06-01 03:05:00 0 days 00:50:00            11   0.654049    0.634391\n2018-04-04 03:30:00 2018-04-04 04:20:00 0 days 00:50:00            11   0.672540    0.631323\n2019-05-14 04:40:00 2019-05-14 05:30:00 0 days 00:50:00            11   0.655558    0.631178\n2020-07-26 06:40:00 2020-07-26 07:25:00 0 days 00:45:00            10   0.714308    0.678519\n2017-11-04 09:15:00 2017-11-04 10:00:00 0 days 00:45:00            10   0.681087    0.664001\n2018-05-08 02:35:00 2018-05-08 03:20:00 0 days 00:45:00            10   0.706280    0.657589\n2017-03-29 21:40:00 2017-03-29 22:25:00 0 days 00:45:00            10   0.692829    0.656497\n2018-07-19 06:50:00 2018-07-19 07:35:00 0 days 00:45:00            10   0.695138    0.652701\n2018-06-10 03:40:00 2018-06-10 04:25:00 0 days 00:45:00            10   0.674620    0.652472\n2017-07-20 09:10:00 2017-07-20 09:55:00 0 days 00:45:00            10   0.680352    0.650961\n2018-01-16 18:55:00 2018-01-16 19:40:00 0 days 00:45:00            10   0.697514    0.650581\n2019-08-31 04:40:00 2019-08-31 05:25:00 0 days 00:45:00            10   0.705638    0.646117\n2018-05-04 14:20:00 2018-05-04 15:05:00 0 days 00:45:00            10   0.686574    0.645127\n2017-01-23 14:55:00 2017-01-23 15:40:00 0 days 00:45:00            10   0.670656    0.642468\n2019-11-08 20:15:00 2019-11-08 21:00:00 0 days 00:45:00            10   0.692860    0.641511\n2018-03-20 00:15:00 2018-03-20 01:00:00 0 days 00:45:00            10   0.675096    0.640299\n2018-05-01 14:55:00 2018-05-01 15:40:00 0 days 00:45:00            10   0.665278    0.638260\n2017-03-02 07:35:00 2017-03-02 08:20:00 0 days 00:45:00            10   0.655521    0.636280\n2020-07-26 12:10:00 2020-07-26 12:55:00 0 days 00:45:00            10   0.664933    0.630682\n2019-03-09 05:55:00 2019-03-09 06:40:00 0 days 00:45:00            10   0.675374    0.623476\n2018-05-09 12:05:00 2018-05-09 12:45:00 0 days 00:40:00             9   0.723763    0.691307\n2018-08-06 16:45:00 2018-08-06 17:25:00 0 days 00:40:00             9   0.707103    0.664035\n2018-05-10 11:15:00 2018-05-10 11:55:00 0 days 00:40:00             9   0.685283    0.659305\n2019-04-04 14:50:00 2019-04-04 15:30:00 0 days 00:40:00             9   0.709314    0.656272\n2018-11-13 17:15:00 2018-11-13 17:55:00 0 days 00:40:00             9   0.685402    0.651997\n2017-03-25 03:30:00 2017-03-25 04:10:00 0 days 00:40:00             9   0.683281    0.651897\n2020-02-23 10:40:00 2020-02-23 11:20:00 0 days 00:40:00             9   0.675180    0.651837\n2019-04-30 12:15:00 2019-04-30 12:55:00 0 days 00:40:00             9   0.664524    0.649433\n2018-10-25 17:00:00 2018-10-25 17:40:00 0 days 00:40:00             9   0.688284    0.646595\n2017-06-22 06:10:00 2017-06-22 06:50:00 0 days 00:40:00             9   0.674822    0.643114\n2020-03-22 19:50:00 2020-03-22 20:30:00 0 days 00:40:00             9   0.675093    0.642607\n2017-04-03 15:00:00 2017-04-03 15:40:00 0 days 00:40:00             9   0.688008    0.642073\n2017-04-07 01:00:00 2017-04-07 01:40:00 0 days 00:40:00             9   0.674000    0.641474\n2018-11-05 11:10:00 2018-11-05 11:50:00 0 days 00:40:00             9   0.662625    0.639403\n2017-12-27 20:20:00 2017-12-27 21:00:00 0 days 00:40:00             9   0.682968    0.638719\n2018-06-05 11:50:00 2018-06-05 12:30:00 0 days 00:40:00             9   0.655396    0.634081\n2017-01-25 17:45:00 2017-01-25 18:25:00 0 days 00:40:00             9   0.661168    0.633905\n2017-04-29 00:30:00 2017-04-29 01:10:00 0 days 00:40:00             9   0.665420    0.632261\n2019-10-26 15:10:00 2019-10-26 15:50:00 0 days 00:40:00             9   0.652050    0.629428\n2018-03-08 01:15:00 2018-03-08 01:55:00 0 days 00:40:00             9   0.656051    0.625851\n2019-07-01 03:05:00 2019-07-01 03:45:00 0 days 00:40:00             9   0.648977    0.625708\n2018-06-28 11:15:00 2018-06-28 11:55:00 0 days 00:40:00             9   0.652528    0.625450\n2018-05-09 13:50:00 2018-05-09 14:30:00 0 days 00:40:00             9   0.636631    0.619644\n2018-09-25 15:30:00 2018-09-25 16:10:00 0 days 00:40:00             9   0.644080    0.617072\n2018-08-21 12:10:00 2018-08-21 12:45:00 0 days 00:35:00             8   0.702679    0.666357\n2019-03-18 15:50:00 2019-03-18 16:25:00 0 days 00:35:00             8   0.713247    0.649268\n2017-05-31 22:30:00 2017-05-31 23:05:00 0 days 00:35:00             8   0.681397    0.647499\n2018-02-06 08:00:00 2018-02-06 08:35:00 0 days 00:35:00             8   0.686792    0.645931\n2017-09-09 12:55:00 2017-09-09 13:30:00 0 days 00:35:00             8   0.683778    0.641615\n2018-06-27 16:20:00 2018-06-27 16:55:00 0 days 00:35:00             8   0.656266    0.640953\n2017-06-06 14:20:00 2017-06-06 14:55:00 0 days 00:35:00             8   0.668551    0.638922\n2018-02-17 22:20:00 2018-02-17 22:55:00 0 days 00:35:00             8   0.694356    0.635840\n2019-08-17 12:55:00 2019-08-17 13:30:00 0 days 00:35:00             8   0.669244    0.635641\n2017-03-30 22:05:00 2017-03-30 22:40:00 0 days 00:35:00             8   0.671563    0.635632\n2019-05-14 09:10:00 2019-05-14 09:45:00 0 days 00:35:00             8   0.649492    0.632752\n2017-11-16 19:30:00 2017-11-16 20:05:00 0 days 00:35:00             8   0.662482    0.632085\n2017-06-12 13:35:00 2017-06-12 14:10:00 0 days 00:35:00             8   0.654503    0.630619\n2018-06-19 14:55:00 2018-06-19 15:30:00 0 days 00:35:00             8   0.653286    0.628466\n2019-11-20 17:25:00 2019-11-20 18:00:00 0 days 00:35:00             8   0.656347    0.627532\n2018-08-12 15:30:00 2018-08-12 16:05:00 0 days 00:35:00             8   0.636867    0.620269\n2018-03-19 05:00:00 2018-03-19 05:35:00 0 days 00:35:00             8   0.622616    0.615184\n2017-07-28 01:10:00 2017-07-28 01:40:00 0 days 00:30:00             7   0.702581    0.663094\n2018-11-13 14:35:00 2018-11-13 15:05:00 0 days 00:30:00             7   0.687874    0.654836\n2017-04-04 17:15:00 2017-04-04 17:45:00 0 days 00:30:00             7   0.707495    0.654655\n2017-06-16 22:50:00 2017-06-16 23:20:00 0 days 00:30:00             7   0.700174    0.652193\n2018-03-21 03:45:00 2018-03-21 04:15:00 0 days 00:30:00             7   0.678381    0.646201\n2017-10-20 04:40:00 2017-10-20 05:10:00 0 days 00:30:00             7   0.675322    0.644877\n2017-09-19 02:30:00 2017-09-19 03:00:00 0 days 00:30:00             7   0.690892    0.641646\n2018-02-22 13:10:00 2018-02-22 13:40:00 0 days 00:30:00             7   0.669212    0.641588\n2019-10-27 16:55:00 2019-10-27 17:25:00 0 days 00:30:00             7   0.677016    0.638898\n2017-06-24 20:25:00 2017-06-24 20:55:00 0 days 00:30:00             7   0.677335    0.637976\n2018-06-27 15:20:00 2018-06-27 15:50:00 0 days 00:30:00             7   0.656699    0.637115\n2018-07-19 07:50:00 2018-07-19 08:20:00 0 days 00:30:00             7   0.663845    0.636267\n2019-05-14 03:20:00 2019-05-14 03:50:00 0 days 00:30:00             7   0.661148    0.634750\n2018-05-23 22:50:00 2018-05-23 23:20:00 0 days 00:30:00             7   0.665089    0.634588\n2018-04-14 09:20:00 2018-04-14 09:50:00 0 days 00:30:00             7   0.658545    0.634083\n2018-07-14 10:15:00 2018-07-14 10:45:00 0 days 00:30:00             7   0.659948    0.633304\n2017-10-27 18:20:00 2017-10-27 18:50:00 0 days 00:30:00             7   0.657355    0.632478\n2020-05-26 11:10:00 2020-05-26 11:40:00 0 days 00:30:00             7   0.654333    0.632449\n2018-09-17 16:55:00 2018-09-17 17:25:00 0 days 00:30:00             7  

In [34]:
final_periods["year"] = final_periods["start_time"].dt.year

final_periods["year"].value_counts().sort_index()

year
2017     80
2018    102
2019     49
2020     21
Name: count, dtype: int64

10 strongest sustained abnormal periods

In [35]:
final_periods.sort_values(
    "mean_score",
    ascending=False
).head(10)

,start_time,end_time,duration,observations,max_score,mean_score,year
79,2018-11-27 05:40:00,2018-11-27 06:30:00,0 days 00:50:00,11,0.740618,0.703044,2018
34,2018-02-11 12:15:00,2018-02-11 13:10:00,0 days 00:55:00,12,0.725777,0.694199,2018
152,2018-05-09 12:05:00,2018-05-09 12:45:00,0 days 00:40:00,9,0.723763,0.691307,2018
26,2018-09-15 08:35:00,2018-09-15 09:35:00,0 days 01:00:00,13,0.713336,0.687895,2018
35,2018-05-31 19:10:00,2018-05-31 20:05:00,0 days 00:55:00,12,0.723424,0.685048,2018
36,2018-08-22 18:10:00,2018-08-22 19:05:00,0 days 00:55:00,12,0.714466,0.683196,2018
80,2018-07-15 01:45:00,2018-07-15 02:35:00,0 days 00:50:00,11,0.714736,0.681778,2018
37,2017-12-12 22:00:00,2017-12-12 22:55:00,0 days 00:55:00,12,0.722345,0.681088,2017
81,2019-02-25 14:50:00,2019-02-25 15:40:00,0 days 00:50:00,11,0.714483,0.680432,2019
38,2017-06-08 16:30:00,2017-06-08 17:25:00,0 days 00:55:00,12,0.701223,0.678640,2017

In [36]:
period = df[
    (df["time"] >= "2018-11-27 05:40:00") &
    (df["time"] <= "2018-11-27 06:30:00")
]

sensor_cols = [
    "Cyclone_Inlet_Gas_Temp",
    "Cyclone_Gas_Outlet_Temp",
    "Cyclone_Outlet_Gas_draft",
    "Cyclone_cone_draft",
    "Cyclone_Inlet_Draft",
    "Cyclone_Material_Temp"
]

period[sensor_cols].agg(
    ["mean", "std", "min", "max"]
).T

                                mean        std     min     max
Cyclone_Inlet_Gas_Temp    750.469091  13.691761  731.14  777.18
Cyclone_Gas_Outlet_Temp   716.136364  10.987535  702.10  740.82
Cyclone_Outlet_Gas_draft   19.517273   7.954751   -4.27   23.52
Cyclone_cone_draft         -4.230000   7.426220  -26.62   -1.82
Cyclone_Inlet_Draft        16.991818   5.833522   -0.38   20.05
Cyclone_Material_Temp     547.530909  43.641036  490.26  640.44

In [37]:
# Create a readable summary of the detected abnormal periods

sensor_cols = [
    "Cyclone_Inlet_Gas_Temp",
    "Cyclone_Gas_Outlet_Temp",
    "Cyclone_Outlet_Gas_draft",
    "Cyclone_cone_draft",
    "Cyclone_Inlet_Draft",
    "Cyclone_Material_Temp"
]

# Overall normal reference statistics
normal_stats = df[sensor_cols].agg(["mean", "std"])

results = []

for _, row in final_periods.iterrows():

    period = df[
        (df["time"] >= row["start_time"]) &
        (df["time"] <= row["end_time"])
    ]

    abnormal_sensors = []

    for sensor in sensor_cols:
        period_mean = period[sensor].mean()
        normal_mean = normal_stats.loc["mean", sensor]
        normal_std = normal_stats.loc["std", sensor]

        if normal_std > 0:
            deviation = abs(period_mean - normal_mean) / normal_std

            if deviation >= 2:
                abnormal_sensors.append(sensor)

    results.append({
        "start_time": row["start_time"],
        "end_time": row["end_time"],
        "duration": row["duration"],
        "mean_anomaly_score": row["mean_score"],
        "max_anomaly_score": row["max_score"],
        "abnormal_sensors": ", ".join(abnormal_sensors)
    })

abnormal_period_report = pd.DataFrame(results)

abnormal_period_report.head(20)

,start_time,end_time,duration,mean_anomaly_score,max_anomaly_score,abnormal_sensors
0,2018-02-28 19:00:00,2018-02-28 21:00:00,0 days 02:00:00,0.648336,0.696930,
1,2020-07-19 04:45:00,2020-07-19 06:30:00,0 days 01:45:00,0.664764,0.706428,
2,2018-05-16 20:45:00,2018-05-16 22:25:00,0 days 01:40:00,0.670374,0.722930,
3,2018-12-10 18:40:00,2018-12-10 20:20:00,0 days 01:40:00,0.659558,0.714939,
4,2017-06-01 08:15:00,2017-06-01 09:45:00,0 days 01:30:00,0.645131,0.692856,
5,2017-06-03 16:05:00,2017-06-03 17:30:00,0 days 01:25:00,0.661224,0.719391,
6,2018-06-19 23:25:00,2018-06-20 00:50:00,0 days 01:25:00,0.642903,0.676919,
7,2018-07-10 13:35:00,2018-07-10 15:00:00,0 days 01:25:00,0.631263,0.690323,
8,2018-05-16 10:55:00,2018-05-16 12:10:00,0 days 01:15:00,0.671819,0.719836,
9,2018-02-24 09:10:00,2018-02-24 10:25:00,0 days 01:15:00,0.656666,0.705654,
10,2020-05-21 11:20:00,2020-05-21 12:35:00,0 days 01:15:00,0.654240,0.698581,
11,2017-12-12 23:30:00,2017-12-13 00:45:00,0 days 01:15:00,0.645479,0.711089,
12,2019-10-29 11:25:00,2019-10-29 12:40:00,0 days 01:15:00,0.643526,0.706102,
13,2017-12-25 07:35:00,2017-12-25 08:50:00,0 days 01:15:00,0.627329,0.674024,
14,2017-06-09 02:15:00,2017-06-09 03:25:00,0 days 01:10:00,0.677256,0.717103,
15,2017-09-09 04:45:00,2017-09-09 05:55:00,0 days 01:10:00,0.670178,0.737177,
16,2017-12-25 06:15:00,2017-12-25 07:25:00,0 days 01:10:00,0.663059,0.700589,
17,2017-06-14 11:30:00,2017-06-14 12:40:00,0 days 01:10:00,0.661344,0.715389,
18,2017-11-01 19:30:00,2017-11-01 20:40:00,0 days 01:10:00,0.659747,0.712905,
19,2017-08-05 04:20:00,2017-08-05 05:30:00,0 days 01:10:00,0.650730,0.688411,

In [38]:
# Create a simple automatic description for each abnormal period

def describe_period(row, df):
    period = df[
        (df["time"] >= row["start_time"]) &
        (df["time"] <= row["end_time"])
    ]

    descriptions = []
    # Temperature behavior
    inlet_temp_range = period["Cyclone_Inlet_Gas_Temp"].max() - period["Cyclone_Inlet_Gas_Temp"].min()
    outlet_temp_range = period["Cyclone_Gas_Outlet_Temp"].max() - period["Cyclone_Gas_Outlet_Temp"].min()

    if inlet_temp_range > 150 or outlet_temp_range > 150:
        descriptions.append("large temperature variation")
    outlet_draft_range = (
        period["Cyclone_Outlet_Gas_draft"].max()
        - period["Cyclone_Outlet_Gas_draft"].min()
    )

    cone_draft_range = (
        period["Cyclone_cone_draft"].max()
        - period["Cyclone_cone_draft"].min()
    )

    if outlet_draft_range > 150 or cone_draft_range > 150:
        descriptions.append("large draft variation")
    material_range = (
        period["Cyclone_Material_Temp"].max()
        - period["Cyclone_Material_Temp"].min()
    )

    if material_range > 150:
        descriptions.append("large material-temperature variation")
    if not descriptions:
        descriptions.append("unusual multivariate process behavior")
    return ", ".join(descriptions)

final_periods["behavior"] = final_periods.apply(
    lambda row: describe_period(row, model_data),
    axis=1
)

final_periods.head(20)

,start_time,end_time,duration,observations,max_score,mean_score,year,behavior
0,2018-02-28 19:00:00,2018-02-28 21:00:00,0 days 02:00:00,25,0.696930,0.648336,2018,"large temperature variation, large draft varia..."
1,2020-07-19 04:45:00,2020-07-19 06:30:00,0 days 01:45:00,22,0.706428,0.664764,2020,"large temperature variation, large draft varia..."
2,2018-05-16 20:45:00,2018-05-16 22:25:00,0 days 01:40:00,21,0.722930,0.670374,2018,"large temperature variation, large draft varia..."
3,2018-12-10 18:40:00,2018-12-10 20:20:00,0 days 01:40:00,21,0.714939,0.659558,2018,"large temperature variation, large draft varia..."
4,2017-06-01 08:15:00,2017-06-01 09:45:00,0 days 01:30:00,19,0.692856,0.645131,2017,"large temperature variation, large draft varia..."
5,2017-06-03 16:05:00,2017-06-03 17:30:00,0 days 01:25:00,18,0.719391,0.661224,2017,"large temperature variation, large draft varia..."
6,2018-06-19 23:25:00,2018-06-20 00:50:00,0 days 01:25:00,18,0.676919,0.642903,2018,"large temperature variation, large draft varia..."
7,2018-07-10 13:35:00,2018-07-10 15:00:00,0 days 01:25:00,18,0.690323,0.631263,2018,"large temperature variation, large material-te..."
8,2018-05-16 10:55:00,2018-05-16 12:10:00,0 days 01:15:00,16,0.719836,0.671819,2018,"large temperature variation, large material-te..."
9,2018-02-24 09:10:00,2018-02-24 10:25:00,0 days 01:15:00,16,0.705654,0.656666,2018,"large temperature variation, large draft varia..."
10,2020-05-21 11:20:00,2020-05-21 12:35:00,0 days 01:15:00,16,0.698581,0.654240,2020,"large temperature variation, large draft varia..."
11,2017-12-12 23:30:00,2017-12-13 00:45:00,0 days 01:15:00,16,0.711089,0.645479,2017,"large temperature variation, large material-te..."
12,2019-10-29 11:25:00,2019-10-29 12:40:00,0 days 01:15:00,16,0.706102,0.643526,2019,"large temperature variation, large draft varia..."
13,2017-12-25 07:35:00,2017-12-25 08:50:00,0 days 01:15:00,16,0.674024,0.627329,2017,"large temperature variation, large material-te..."
14,2017-06-09 02:15:00,2017-06-09 03:25:00,0 days 01:10:00,15,0.717103,0.677256,2017,"large temperature variation, large material-te..."
15,2017-09-09 04:45:00,2017-09-09 05:55:00,0 days 01:10:00,15,0.737177,0.670178,2017,"large temperature variation, large draft varia..."
16,2017-12-25 06:15:00,2017-12-25 07:25:00,0 days 01:10:00,15,0.700589,0.663059,2017,"large temperature variation, large material-te..."
17,2017-06-14 11:30:00,2017-06-14 12:40:00,0 days 01:10:00,15,0.715389,0.661344,2017,"large temperature variation, large draft varia..."
18,2017-11-01 19:30:00,2017-11-01 20:40:00,0 days 01:10:00,15,0.712905,0.659747,2017,"large temperature variation, large draft varia..."
19,2017-08-05 04:20:00,2017-08-05 05:30:00,0 days 01:10:00,15,0.688411,0.650730,2017,"large temperature variation, large draft varia..."

final output

In [39]:
final_periods.to_csv(
    "detected_abnormal_periods.csv",
    index=False
)

print("Detected abnormal periods:", len(final_periods))
print("Saved to: detected_abnormal_periods.csv")

Detected abnormal periods: 252
Saved to: detected_abnormal_periods.csv

In [40]:
final_periods[
    [
        "start_time",
        "end_time",
        "duration",
        "mean_score",
        "max_score",
        "behavior"
    ]
].head(20)

,start_time,end_time,duration,mean_score,max_score,behavior
0,2018-02-28 19:00:00,2018-02-28 21:00:00,0 days 02:00:00,0.648336,0.696930,"large temperature variation, large draft varia..."
1,2020-07-19 04:45:00,2020-07-19 06:30:00,0 days 01:45:00,0.664764,0.706428,"large temperature variation, large draft varia..."
2,2018-05-16 20:45:00,2018-05-16 22:25:00,0 days 01:40:00,0.670374,0.722930,"large temperature variation, large draft varia..."
3,2018-12-10 18:40:00,2018-12-10 20:20:00,0 days 01:40:00,0.659558,0.714939,"large temperature variation, large draft varia..."
4,2017-06-01 08:15:00,2017-06-01 09:45:00,0 days 01:30:00,0.645131,0.692856,"large temperature variation, large draft varia..."
5,2017-06-03 16:05:00,2017-06-03 17:30:00,0 days 01:25:00,0.661224,0.719391,"large temperature variation, large draft varia..."
6,2018-06-19 23:25:00,2018-06-20 00:50:00,0 days 01:25:00,0.642903,0.676919,"large temperature variation, large draft varia..."
7,2018-07-10 13:35:00,2018-07-10 15:00:00,0 days 01:25:00,0.631263,0.690323,"large temperature variation, large material-te..."
8,2018-05-16 10:55:00,2018-05-16 12:10:00,0 days 01:15:00,0.671819,0.719836,"large temperature variation, large material-te..."
9,2018-02-24 09:10:00,2018-02-24 10:25:00,0 days 01:15:00,0.656666,0.705654,"large temperature variation, large draft varia..."
10,2020-05-21 11:20:00,2020-05-21 12:35:00,0 days 01:15:00,0.654240,0.698581,"large temperature variation, large draft varia..."
11,2017-12-12 23:30:00,2017-12-13 00:45:00,0 days 01:15:00,0.645479,0.711089,"large temperature variation, large material-te..."
12,2019-10-29 11:25:00,2019-10-29 12:40:00,0 days 01:15:00,0.643526,0.706102,"large temperature variation, large draft varia..."
13,2017-12-25 07:35:00,2017-12-25 08:50:00,0 days 01:15:00,0.627329,0.674024,"large temperature variation, large material-te..."
14,2017-06-09 02:15:00,2017-06-09 03:25:00,0 days 01:10:00,0.677256,0.717103,"large temperature variation, large material-te..."
15,2017-09-09 04:45:00,2017-09-09 05:55:00,0 days 01:10:00,0.670178,0.737177,"large temperature variation, large draft varia..."
16,2017-12-25 06:15:00,2017-12-25 07:25:00,0 days 01:10:00,0.663059,0.700589,"large temperature variation, large material-te..."
17,2017-06-14 11:30:00,2017-06-14 12:40:00,0 days 01:10:00,0.661344,0.715389,"large temperature variation, large draft varia..."
18,2017-11-01 19:30:00,2017-11-01 20:40:00,0 days 01:10:00,0.659747,0.712905,"large temperature variation, large draft varia..."
19,2017-08-05 04:20:00,2017-08-05 05:30:00,0 days 01:10:00,0.650730,0.688411,"large temperature variation, large draft varia..."

overall result

In [ ]:
print("Total abnormal periods:", len(final_periods))
print("\nPeriods by year:")
print(
    final_periods["start_time"]
    .dt.year
    .value_counts()
    .sort_index()
)

print("\nTotal abnormal duration by year:")
year_duration = (
    final_periods
    .assign(year=final_periods["start_time"].dt.year)
    .groupby("year")["duration"]
    .sum()
)

print(year_duration)

print("\nOverall abnormal duration:")
print(final_periods["duration"].sum())

Total abnormal periods: 252

Periods by year:
start_time
2017     80
2018    102
2019     49
2020     21
Name: count, dtype: int64

Total abnormal duration by year:
year
2017   2 days 14:30:00
2018   3 days 07:10:00
2019   1 days 12:35:00
2020   0 days 17:40:00
Name: duration, dtype: timedelta64[us]

Overall abnormal duration:
8 days 03:55:00

In [44]:
print(final_periods.columns.tolist())

['start_time', 'end_time', 'duration', 'observations', 'max_score', 'mean_score', 'year', 'behavior']

The model identifying the strongest periods

In [45]:
top_10 = (
    final_periods
    .sort_values("mean_score", ascending=False)
    .head(10)
)

top_10[
    [
        "start_time",
        "end_time",
        "duration",
        "mean_score",
        "max_score"
    ]
]

,start_time,end_time,duration,mean_score,max_score
79,2018-11-27 05:40:00,2018-11-27 06:30:00,0 days 00:50:00,0.703044,0.740618
34,2018-02-11 12:15:00,2018-02-11 13:10:00,0 days 00:55:00,0.694199,0.725777
152,2018-05-09 12:05:00,2018-05-09 12:45:00,0 days 00:40:00,0.691307,0.723763
26,2018-09-15 08:35:00,2018-09-15 09:35:00,0 days 01:00:00,0.687895,0.713336
35,2018-05-31 19:10:00,2018-05-31 20:05:00,0 days 00:55:00,0.685048,0.723424
36,2018-08-22 18:10:00,2018-08-22 19:05:00,0 days 00:55:00,0.683196,0.714466
80,2018-07-15 01:45:00,2018-07-15 02:35:00,0 days 00:50:00,0.681778,0.714736
37,2017-12-12 22:00:00,2017-12-12 22:55:00,0 days 00:55:00,0.681088,0.722345
81,2019-02-25 14:50:00,2019-02-25 15:40:00,0 days 00:50:00,0.680432,0.714483
38,2017-06-08 16:30:00,2017-06-08 17:25:00,0 days 00:55:00,0.678640,0.701223

In [46]:
top_10[
    [
        "start_time",
        "end_time",
        "duration",
        "mean_score",
        "max_score",
        "behavior"
    ]
]

,start_time,end_time,duration,mean_score,max_score,behavior
79,2018-11-27 05:40:00,2018-11-27 06:30:00,0 days 00:50:00,0.703044,0.740618,large material-temperature variation
34,2018-02-11 12:15:00,2018-02-11 13:10:00,0 days 00:55:00,0.694199,0.725777,"large draft variation, large material-temperat..."
152,2018-05-09 12:05:00,2018-05-09 12:45:00,0 days 00:40:00,0.691307,0.723763,large material-temperature variation
26,2018-09-15 08:35:00,2018-09-15 09:35:00,0 days 01:00:00,0.687895,0.713336,"large temperature variation, large draft varia..."
35,2018-05-31 19:10:00,2018-05-31 20:05:00,0 days 00:55:00,0.685048,0.723424,large material-temperature variation
36,2018-08-22 18:10:00,2018-08-22 19:05:00,0 days 00:55:00,0.683196,0.714466,"large temperature variation, large material-te..."
80,2018-07-15 01:45:00,2018-07-15 02:35:00,0 days 00:50:00,0.681778,0.714736,large material-temperature variation
37,2017-12-12 22:00:00,2017-12-12 22:55:00,0 days 00:55:00,0.681088,0.722345,"large draft variation, large material-temperat..."
81,2019-02-25 14:50:00,2019-02-25 15:40:00,0 days 00:50:00,0.680432,0.714483,large material-temperature variation
38,2017-06-08 16:30:00,2017-06-08 17:25:00,0 days 00:55:00,0.678640,0.701223,large material-temperature variation

In [47]:
# Select the strongest abnormal period
top_period = top_10.iloc[0]

start = top_period["start_time"]
end = top_period["end_time"]

# Get the abnormal period
abnormal = model_data[
    (model_data["time"] >= start) &
    (model_data["time"] <= end)
]

# Get 1 hour before and after for comparison
before = model_data[
    (model_data["time"] >= start - pd.Timedelta(hours=1)) &
    (model_data["time"] < start)
]

after = model_data[
    (model_data["time"] > end) &
    (model_data["time"] <= end + pd.Timedelta(hours=1))
]

print("ABNORMAL PERIOD")
print(start, "to", end)

print("\nSensor values during abnormal period:")
print(
    abnormal[sensor_cols]
    .agg(["mean", "min", "max"])
    .round(2)
)

ABNORMAL PERIOD
2018-11-27 05:40:00 to 2018-11-27 06:30:00

Sensor values during abnormal period:
      Cyclone_Inlet_Gas_Temp  Cyclone_Gas_Outlet_Temp  \
mean                  750.47                   716.14
min                   731.14                   702.10
max                   777.18                   740.82

      Cyclone_Outlet_Gas_draft  Cyclone_cone_draft  Cyclone_Inlet_Draft  \
mean                     19.52               -4.23                16.99
min                      -4.27              -26.62                -0.38
max                      23.52               -1.82                20.05

      Cyclone_Material_Temp
mean                 547.53
min                  490.26
max                  640.44

In [49]:
def describe_period_change(row, df):
    start = row["start_time"]
    end = row["end_time"]

    # Abnormal period
    abnormal = df[
        (df["time"] >= start) &
        (df["time"] <= end)
    ]

    # 1 hour before abnormal period
    before = df[
        (df["time"] >= start - pd.Timedelta(hours=1)) &
        (df["time"] < start)
    ]

    if abnormal.empty or before.empty:
        return "unusual multivariate process behavior"

    descriptions = []

    # Compare average values before vs during
    for sensor in sensor_cols:
        before_mean = before[sensor].mean()
        abnormal_mean = abnormal[sensor].mean()

        if pd.isna(before_mean) or pd.isna(abnormal_mean):
            continue

        change = abnormal_mean - before_mean

        # Use percentage change where appropriate
        if abs(before_mean) > 20:
            pct_change = abs(change / before_mean) * 100
        else:
            pct_change = 0

        # Temperature sensors
        if sensor in [
            "Cyclone_Inlet_Gas_Temp",
            "Cyclone_Gas_Outlet_Temp",
            "Cyclone_Material_Temp"
        ]:
            if pct_change >= 15:
                if change < 0:
                    descriptions.append(
                        f"{sensor.replace('Cyclone_', '').replace('_', ' ')} decrease"
                    )
                else:
                    descriptions.append(
                        f"{sensor.replace('Cyclone_', '').replace('_', ' ')} increase"
                    )

        # Draft sensors
        elif sensor in [
            "Cyclone_Outlet_Gas_draft",
            "Cyclone_cone_draft",
            "Cyclone_Inlet_Draft"
        ]:
            if abs(change) >= 50:
                descriptions.append(
                    f"{sensor.replace('Cyclone_', '').replace('_', ' ')} shift"
                )

    if not descriptions:
        return "unusual multivariate process behavior"

    # Keep maximum 3 descriptions so the table stays readable
    return " + ".join(descriptions[:3])


final_periods["behavior"] = final_periods.apply(
    lambda row: describe_period_change(row, model_data),
    axis=1
)

In [50]:
top_10 = (
    final_periods
    .sort_values("mean_score", ascending=False)
    .head(10)
)

top_10[
    [
        "start_time",
        "end_time",
        "duration",
        "mean_score",
        "max_score",
        "behavior"
    ]
]

,start_time,end_time,duration,mean_score,max_score,behavior
79,2018-11-27 05:40:00,2018-11-27 06:30:00,0 days 00:50:00,0.703044,0.740618,Inlet Gas Temp decrease + Gas Outlet Temp decr...
34,2018-02-11 12:15:00,2018-02-11 13:10:00,0 days 00:55:00,0.694199,0.725777,Inlet Gas Temp decrease + Gas Outlet Temp decr...
152,2018-05-09 12:05:00,2018-05-09 12:45:00,0 days 00:40:00,0.691307,0.723763,Inlet Gas Temp decrease + Gas Outlet Temp decr...
26,2018-09-15 08:35:00,2018-09-15 09:35:00,0 days 01:00:00,0.687895,0.713336,Inlet Gas Temp decrease + Gas Outlet Temp decr...
35,2018-05-31 19:10:00,2018-05-31 20:05:00,0 days 00:55:00,0.685048,0.723424,Inlet Gas Temp decrease + Gas Outlet Temp decr...
36,2018-08-22 18:10:00,2018-08-22 19:05:00,0 days 00:55:00,0.683196,0.714466,Outlet Gas draft shift + cone draft shift + In...
80,2018-07-15 01:45:00,2018-07-15 02:35:00,0 days 00:50:00,0.681778,0.714736,Outlet Gas draft shift + cone draft shift + In...
37,2017-12-12 22:00:00,2017-12-12 22:55:00,0 days 00:55:00,0.681088,0.722345,Outlet Gas draft shift + cone draft shift + In...
81,2019-02-25 14:50:00,2019-02-25 15:40:00,0 days 00:50:00,0.680432,0.714483,Inlet Gas Temp decrease + Outlet Gas draft shi...
38,2017-06-08 16:30:00,2017-06-08 17:25:00,0 days 00:55:00,0.678640,0.701223,Inlet Gas Temp decrease + Outlet Gas draft shi...

In [51]:
final_periods.to_csv(
    "detected_abnormal_periods.csv",
    index=False
)

print("Final abnormal periods:", len(final_periods))
print("File saved: detected_abnormal_periods.csv")

Final abnormal periods: 252
File saved: detected_abnormal_periods.csv

In [52]:
pd.set_option("display.max_colwidth", None)
top_10[
    [
        "start_time",
        "end_time",
        "duration",
        "mean_score",
        "max_score",
        "behavior"
    ]
]

,start_time,end_time,duration,mean_score,max_score,behavior
79,2018-11-27 05:40:00,2018-11-27 06:30:00,0 days 00:50:00,0.703044,0.740618,Inlet Gas Temp decrease + Gas Outlet Temp decrease + Outlet Gas draft shift
34,2018-02-11 12:15:00,2018-02-11 13:10:00,0 days 00:55:00,0.694199,0.725777,Inlet Gas Temp decrease + Gas Outlet Temp decrease + Outlet Gas draft shift
152,2018-05-09 12:05:00,2018-05-09 12:45:00,0 days 00:40:00,0.691307,0.723763,Inlet Gas Temp decrease + Gas Outlet Temp decrease + Outlet Gas draft shift
26,2018-09-15 08:35:00,2018-09-15 09:35:00,0 days 01:00:00,0.687895,0.713336,Inlet Gas Temp decrease + Gas Outlet Temp decrease + Outlet Gas draft shift
35,2018-05-31 19:10:00,2018-05-31 20:05:00,0 days 00:55:00,0.685048,0.723424,Inlet Gas Temp decrease + Gas Outlet Temp decrease + Outlet Gas draft shift
36,2018-08-22 18:10:00,2018-08-22 19:05:00,0 days 00:55:00,0.683196,0.714466,Outlet Gas draft shift + cone draft shift + Inlet Draft shift
80,2018-07-15 01:45:00,2018-07-15 02:35:00,0 days 00:50:00,0.681778,0.714736,Outlet Gas draft shift + cone draft shift + Inlet Draft shift
37,2017-12-12 22:00:00,2017-12-12 22:55:00,0 days 00:55:00,0.681088,0.722345,Outlet Gas draft shift + cone draft shift + Inlet Draft shift
81,2019-02-25 14:50:00,2019-02-25 15:40:00,0 days 00:50:00,0.680432,0.714483,Inlet Gas Temp decrease + Outlet Gas draft shift + cone draft shift
38,2017-06-08 16:30:00,2017-06-08 17:25:00,0 days 00:55:00,0.678640,0.701223,Inlet Gas Temp decrease + Outlet Gas draft shift + cone draft shift

In [53]:
final_periods.to_csv(
    "detected_abnormal_periods.csv",
    index=False
)

print("Total detected abnormal periods:", len(final_periods))

Total detected abnormal periods: 252

In [54]:
year_summary = (
    final_periods
    .assign(year=final_periods["start_time"].dt.year)
    .groupby("year")
    .agg(
        abnormal_periods=("start_time", "count"),
        total_duration=("duration", "sum"),
        highest_mean_score=("mean_score", "max"),
        highest_max_score=("max_score", "max")
    )
    .reset_index()
)

year_summary

,year,abnormal_periods,total_duration,highest_mean_score,highest_max_score
0,2017,80,2 days 14:30:00,0.681088,0.737177
1,2018,102,3 days 07:10:00,0.703044,0.740618
2,2019,49,1 days 12:35:00,0.680432,0.714515
3,2020,21,0 days 17:40:00,0.678519,0.714308

In [55]:
print("Total abnormal periods:", len(final_periods))
print("Total abnormal duration:", final_periods["duration"].sum())

Total abnormal periods: 252
Total abnormal duration: 8 days 03:55:00

In [56]:
model_data[["time", "anomaly_score", "anomaly_99"]].to_csv(
    "anomaly_scores.csv",
    index=False
)

print("Saved anomaly_scores.csv")
print("Rows:", len(model_data))

Saved anomaly_scores.csv
Rows: 374761